Repository project-oak/oak, pull requests merged in 2020-10, with the labels that each got.

#1538 Event for node creation. Prune old things. A TODO
  experimental/ni_coq/vfiles/EvAugSemantics.v
  experimental/ni_coq/vfiles/Events.v
  experimental/ni_coq/vfiles/TraceTheorems.v
  experimental/ni_coq/vfiles/Unwind.v
Labels: cla: yes

#1544 Improve graph styles
  oak_runtime/introspection_browser_client/components/StateGraph/index.tsx
Labels: cla: yes

#1396 Update docs for signature labels
  docs/concepts.md
  docs/development.md
  docs/programming-oak.md
Labels: cla: yes

#1543 Merge Trusted Database Wasm modules
  examples/Cargo.lock
  examples/Cargo.toml
  examples/trusted_database/example.toml
  examples/trusted_database/module/rust/Cargo.toml
  examples/trusted_database/module/rust/build.rs
  examples/trusted_database/module/rust/src/database.rs
  examples/trusted_database/module/rust/src/handler.rs
  examples/trusted_database/module/rust/src/lib.rs
  examples/trusted_database/module/rust/src/tests.rs
  examples/trusted_database/module/rust/tests/integration_test.rs
  examples/trusted_database/module_0/rust/Cargo.toml
  examples/trusted_database/module_0/rust/build.rs
  examples/trusted_database/module_1/rust/src/tests.rs
  examples/trusted_database/oak_app_manifest.toml
Labels: cla: yes

#1552 Implement IntoIterator for HeaderMap in oak_services
  experimental/Cargo.lock
  oak_runtime/src/node/http/mod.rs
  oak_services/src/http/mod.rs
Labels: cla: yes

#1535 Lowproj step WriteChannel FlowsTo case
  experimental/ni_coq/vfiles/EvAugSemantics.v
  experimental/ni_coq/vfiles/GenericMap.v
  experimental/ni_coq/vfiles/NIUtilTheorems.v
  experimental/ni_coq/vfiles/PossibilisticNI.v
  experimental/ni_coq/vfiles/Unwind.v
Labels: cla: yes

#1556 WriteChannel step_implies_lowproj_steps proof
  experimental/ni_coq/_CoqProject
  experimental/ni_coq/vfiles/NIUtilTheorems.v
  experimental/ni_coq/vfiles/PossibilisticNI.v
  experimental/ni_coq/vfiles/Unwind.v
Labels: cla: yes

#1557 Create 'unwind' hint db for eauto
  experimental/ni_coq/vfiles/PossibilisticNI.v
Labels: cla: yes

#1548 Fix a race condition in the graph rendering
  oak_runtime/introspection_browser_client/components/StateGraph/index.tsx
Labels: cla: yes

#1554 Render events next to the application graph
  oak_runtime/introspection_browser_client/components/ApplicationStateOverview/index.tsx
  oak_runtime/introspection_browser_client/components/Event/index.tsx
  oak_runtime/introspection_browser_client/components/EventList/index.tsx
  oak_runtime/introspection_browser_client/components/MainTabs/index.tsx
  oak_runtime/introspection_browser_client/components/Root/index.tsx
  oak_runtime/introspection_browser_client/components/StateGraph/index.tsx
  oak_runtime/introspection_browser_client/components/TimeTravelControls/index.tsx
Labels: cla: yes

#1560 Introspection: Add favicon
  oak_runtime/introspection_browser_client/static/favicon.png
  oak_runtime/introspection_browser_client/static/index.html
  oak_runtime/src/introspect.rs
Labels: cla: yes, lang/Rust

#1561 Introspection: (Re)add missing include_bytes! call
  oak_runtime/src/introspect.rs
Labels: cla: yes, lang/Rust

#1562 Automate possibilistic_ni proof and prove no_steps_from_empty
  experimental/ni_coq/vfiles/PossibilisticNI.v
  experimental/ni_coq/vfiles/TraceTheorems.v
Labels: cla: yes

#1564 Introspection: Render details in dialogs for context
  oak_runtime/introspection_browser_client/components/ChannelDetails/index.tsx
  oak_runtime/introspection_browser_client/components/DetailsDialog/index.tsx
  oak_runtime/introspection_browser_client/components/HandleDetails/index.tsx
  oak_runtime/introspection_browser_client/components/NodeDetails/index.tsx
  oak_runtime/introspection_browser_client/components/NotFound/index.tsx
  oak_runtime/introspection_browser_client/components/Root/index.tsx
  oak_runtime/introspection_browser_client/components/StateGraph/index.tsx
Labels: cla: yes

#1539 Add abitests for HTTP server pseudo-node
  examples/Cargo.lock
  examples/abitest/client/cpp/BUILD
  examples/abitest/client/cpp/abitest.cc
  examples/abitest/client/cpp/httplib_config.h
  examples/abitest/client/cpp/httptest.cc
  examples/abitest/client/cpp/httptest.h
  examples/abitest/module_0/rust/Cargo.toml
  examples/abitest/module_0/rust/src/lib.rs
  examples/http_server/example.toml
  examples/http_server/module/src/lib.rs
  oak_runtime/src/node/http/mod.rs
  oak_runtime/src/tls.rs
  runner/src/main.rs
  sdk/rust/oak_tests/src/lib.rs
Labels: cla: yes

#1566 Remove commented code in TIR
  examples/trusted_information_retrieval/module_1/rust/src/lib.rs
Labels: cla: yes

#1563 Introspection: Persist state across links & page refreshes
  oak_runtime/introspection_browser_client/components/Event/index.tsx
  oak_runtime/introspection_browser_client/components/Root/index.tsx
  oak_runtime/introspection_browser_client/package-lock.json
  oak_runtime/introspection_browser_client/package.json
Labels: cla: yes, lang/JavaScript

#1567 Ensure HandleDestroyed event fires before ChannelDestroyed
  oak_runtime/src/lib.rs
Labels: cla: yes, lang/Rust

#1569 Initial web emulator
  experimental/web/README.md
  experimental/web/index.html
Labels: cla: yes

#1572 Rename `Node` to `CommandHandler`.
  docs/programming-oak.md
  examples/abitest/module_0/rust/src/lib.rs
  examples/aggregator/module/rust/src/lib.rs
  examples/chat/module/rust/src/backend.rs
  examples/chat/module/rust/src/lib.rs
  examples/hello_world/module/rust/src/lib.rs
  examples/http_server/module/src/lib.rs
  examples/injection/module/rust/src/lib.rs
  examples/machine_learning/module/rust/src/lib.rs
  examples/private_set_intersection/module/rust/src/lib.rs
  examples/running_average/module/rust/src/lib.rs
  examples/translator/module/rust/src/lib.rs
  examples/trusted_database/module/rust/src/handler.rs
  examples/trusted_database/module/rust/src/lib.rs
  examples/trusted_information_retrieval/module_0/rust/src/lib.rs
  examples/trusted_information_retrieval/module_1/rust/src/lib.rs
  oak_io/src/handle.rs
  oak_io/src/receiver.rs
  sdk/rust/oak/src/grpc/mod.rs
  sdk/rust/oak/src/lib.rs
Labels: cla: yes

#1570 Add an option to compile release Wasm in tests
  examples/abitest/module_0/rust/tests/integration_test.rs
  examples/trusted_database/module/rust/tests/integration_test.rs
  sdk/rust/oak_tests/src/lib.rs
Labels: cla: yes

#1574 Format HTML files with prettier
  experimental/web/index.html
  runner/src/main.rs
Labels: cla: yes

#1571 Rename cargo_path to manifest_path
  sdk/rust/oak_tests/src/lib.rs
Labels: cla: yes

#1573 Parse protobuf messages in web emulator
  experimental/web/index.html
Labels: cla: yes

#1575 Finish proof of step_implies_lowproj_steps_leq
  experimental/ni_coq/vfiles/NIUtilTheorems.v
  experimental/ni_coq/vfiles/PossibilisticNI.v
Labels: cla: yes

#1577 Introspection: Improve dialog styles
  oak_runtime/introspection_browser_client/components/ChannelDetails/index.tsx
  oak_runtime/introspection_browser_client/components/DetailsDialog/index.tsx
  oak_runtime/introspection_browser_client/components/Node/index.tsx
  oak_runtime/introspection_browser_client/components/NodeDetails/index.tsx
  oak_runtime/introspection_browser_client/components/ObjectAsTree/index.tsx
  oak_runtime/introspection_browser_client/components/Root/index.tsx
  oak_runtime/introspection_browser_client/package-lock.json
  oak_runtime/introspection_browser_client/package.json
Labels: cla: yes

#1576 Add set ID to Private Set Intersection
  examples/private_set_intersection/client/cpp/private_set_intersection.cc
  examples/private_set_intersection/client/rust/src/main.rs
  examples/private_set_intersection/example.toml
  examples/private_set_intersection/module/rust/src/lib.rs
  examples/private_set_intersection/module/rust/tests/integration_test.rs
  examples/private_set_intersection/oak_app_manifest.toml
  examples/private_set_intersection/private_set_intersection.sign
  examples/private_set_intersection/proto/private_set_intersection.proto
Labels: cla: yes

#1578 Finish low_proj_steps_implies... + ..._unwind_t; tactics
  experimental/ni_coq/vfiles/PossibilisticNI.v
Labels: cla: yes

#1579 Fix module_path in compile_rust_wasm
  sdk/rust/oak_tests/src/lib.rs
Labels: cla: yes

#1581 Apply all constructors first to automatically construct new state
  experimental/ni_coq/vfiles/PossibilisticNI.v
Labels: cla: yes

#1550 Add MultiWriter and OneshotWriter.
  experimental/Cargo.lock
  experimental/oak_async/Cargo.toml
  experimental/oak_async/src/grpc.rs
  experimental/oak_async/src/lib.rs
Labels: cla: yes

#1585 Implement type safe entrypoint method
  docs/programming-oak.md
  examples/Cargo.lock
  examples/abitest/module_0/rust/src/lib.rs
  examples/abitest/module_1/rust/Cargo.toml
  examples/aggregator/module/rust/src/lib.rs
  examples/chat/module/rust/src/backend.rs
  examples/chat/module/rust/src/lib.rs
  examples/hello_world/module/rust/Cargo.toml
  examples/hello_world/module/rust/src/lib.rs
  examples/http_server/module/src/lib.rs
  examples/injection/module/rust/Cargo.toml
  examples/injection/module/rust/src/lib.rs
  examples/machine_learning/module/rust/Cargo.toml
  examples/machine_learning/module/rust/src/lib.rs
  examples/private_set_intersection/module/rust/Cargo.toml
  examples/private_set_intersection/module/rust/src/lib.rs
  examples/running_average/module/rust/Cargo.toml
  examples/running_average/module/rust/src/lib.rs
  examples/translator/module/rust/Cargo.toml
  examples/translator/module/rust/src/lib.rs
  examples/trusted_database/module/rust/src/handler.rs
  examples/trusted_database/module/rust/src/lib.rs
  examples/trusted_information_retrieval/module_0/rust/src/lib.rs
  examples/trusted_information_retrieval/module_1/rust/src/lib.rs
  sdk/rust/oak/src/lib.rs
Labels: cla: yes

#1590 Update futures_util from 0.3.5 to 0.3.6
  oak_loader/Cargo.lock
  oak_runtime/src/node/grpc/client.rs
  oak_runtime/src/time/mod.rs
Labels: cla: yes

#1596 Remove file watching functionality from Runner
  runner/Cargo.lock
  runner/Cargo.toml
  runner/deny.toml
  runner/src/internal.rs
  runner/src/main.rs
Labels: cla: yes

#1592 Use anyhow for error handling in CommandHandler
  examples/Cargo.lock
  examples/chat/module/rust/Cargo.toml
  examples/chat/module/rust/src/backend.rs
  examples/http_server/module/Cargo.toml
  examples/http_server/module/src/lib.rs
  examples/injection/module/rust/Cargo.toml
  examples/injection/module/rust/src/lib.rs
  examples/trusted_database/module/rust/src/lib.rs
  experimental/Cargo.lock
  sdk/Cargo.lock
  sdk/rust/oak/Cargo.toml
  sdk/rust/oak/src/grpc/mod.rs
  sdk/rust/oak/src/lib.rs
Labels: cla: yes

#1597 Update various versions of tools in Dockerfile
  Dockerfile
  docs/INSTALL-OSX.md
  experimental/Cargo.lock
  experimental/oak_async/Cargo.toml
  oak_derive/tests/visit.rs
  oak_io/src/handle.rs
  oak_loader/src/options.rs
  oak_runtime/src/channel.rs
  runner/src/main.rs
  third_party/roughenough/src/sign.rs
Labels: cla: yes

#1601 Expose label methods from sender and receiver
  sdk/rust/oak/src/io/receiver.rs
  sdk/rust/oak/src/io/sender.rs
Labels: cla: yes

#1588 Introspection: Improve change list
  oak_runtime/introspection_browser_client/components/Event/index.tsx
  oak_runtime/introspection_browser_client/components/EventList/index.tsx
  oak_runtime/introspection_browser_client/components/Root/index.tsx
  oak_runtime/introspection_browser_client/package-lock.json
  oak_runtime/introspection_browser_client/package.json
  oak_runtime/src/lib.rs
  proto/introspection_events.proto
Labels: cla: yes

#1607 Update env_logger
  examples/Cargo.lock
  oak_loader/Cargo.lock
Labels: cla: yes

#1604 Add Rust Oak client library
  docs/programming-oak.md
  examples/Cargo.lock
  examples/Cargo.toml
  examples/hello_world/client/rust/Cargo.toml
  examples/hello_world/client/rust/src/main.rs
  examples/private_set_intersection/client/rust/Cargo.toml
  examples/private_set_intersection/client/rust/src/main.rs
  examples/trusted_database/client/rust/Cargo.toml
  examples/trusted_database/client/rust/src/main.rs
  examples/trusted_information_retrieval/client/rust/Cargo.toml
  examples/trusted_information_retrieval/client/rust/src/main.rs
  experimental/Cargo.lock
  experimental/Cargo.toml
  experimental/benchmark/Cargo.toml
  experimental/benchmark/src/application/native.rs
  oak_abi/src/label/mod.rs
  oak_client/Cargo.lock
  oak_client/Cargo.toml
  oak_client/deny.toml
  oak_client/src/lib.rs
Labels: cla: yes

#1603 Fix state projection defs; finish unobs_step lemma
  experimental/ni_coq/vfiles/LowEquivalences.v
  experimental/ni_coq/vfiles/NIUtilTheorems.v
  experimental/ni_coq/vfiles/PossibilisticNI.v
  experimental/ni_coq/vfiles/RuntimeModel.v
Labels: cla: yes

#1610 Replace tokio::fs::read with std::fs::read
  examples/aggregator/backend/src/main.rs
  examples/authentication/client/src/auth_client.rs
  examples/hello_world/client/rust/src/main.rs
  examples/private_set_intersection/client/rust/src/main.rs
  examples/trusted_database/client/rust/src/main.rs
  examples/trusted_information_retrieval/backend/src/main.rs
  examples/trusted_information_retrieval/client/rust/src/main.rs
  experimental/split_grpc/client/src/main.rs
  experimental/split_grpc/server/src/main.rs
Labels: cla: yes

#1611 Use default gRPC client label in Aggregator
  examples/aggregator/module/rust/src/lib.rs
Labels: cla: yes

#1609 Delete old version of Trusted Information Retrieval
  docs/programming-oak.md
  examples/Cargo.lock
  examples/Cargo.toml
  examples/trusted_information_retrieval/backend/Cargo.toml
  examples/trusted_information_retrieval/backend/build.rs
  examples/trusted_information_retrieval/backend/src/database.rs
  examples/trusted_information_retrieval/backend/src/main.rs
  examples/trusted_information_retrieval/backend/src/tests.rs
  examples/trusted_information_retrieval/client/cpp/BUILD
  examples/trusted_information_retrieval/client/cpp/trusted_information_retrieval.cc
  examples/trusted_information_retrieval/client/rust/Cargo.toml
  examples/trusted_information_retrieval/client/rust/build.rs
  examples/trusted_information_retrieval/client/rust/src/lib.rs
  examples/trusted_information_retrieval/client/rust/src/main.rs
  examples/trusted_information_retrieval/database.toml
  examples/trusted_information_retrieval/example.toml
  examples/trusted_information_retrieval/module_0/rust/Cargo.toml
  examples/trusted_information_retrieval/module_0/rust/build.rs
  examples/trusted_information_retrieval/module_0/rust/src/config.rs
  examples/trusted_information_retrieval/module_0/rust/src/lib.rs
  examples/trusted_information_retrieval/module_0/rust/src/tests.rs
  examples/trusted_information_retrieval/module_0/rust/tests/integration_test.rs
  examples/trusted_information_retrieval/module_1/rust/Cargo.toml
  examples/trusted_information_retrieval/module_1/rust/build.rs
  examples/trusted_information_retrieval/module_1/rust/src/lib.rs
  examples/trusted_information_retrieval/module_1/rust/tests/integration_test.rs
  examples/trusted_information_retrieval/oak_app_manifest.toml
  examples/trusted_information_retrieval/proto/BUILD
  examples/trusted_information_retrieval/proto/database.proto
  examples/trusted_information_retrieval/proto/trusted_information_retrieval.proto
Labels: cla: yes

#1613 Create labeled channel in gRPC client
  sdk/rust/oak/src/grpc/client.rs
Labels: cla: yes

#1582 Preparatory work for meaningful labels to chat example
  docs/programming-oak.md
  examples/Cargo.lock
  examples/Cargo.toml
  examples/chat/README.md
  examples/chat/client/cpp/chat.cc
  examples/chat/module/rust/Cargo.toml
  examples/chat/module/rust/build.rs
  examples/chat/module/rust/src/backend.rs
  examples/chat/module/rust/src/lib.rs
  examples/chat/module/rust/tests/integration_test.rs
  examples/chat/proto/chat.proto
  examples/chat/proto/chat_internal.proto
Labels: cla: yes

#1619 Allow creating Oak nodes for testing
  oak_runtime/src/lib.rs
  oak_runtime/src/node/http/tests.rs
  oak_runtime/src/proxy.rs
  oak_runtime/src/tests.rs
Labels: cla: yes

#1626 Make label compulsory for `oak::channel_create`
  docs/programming-oak.md
  examples/abitest/module_0/rust/src/lib.rs
  examples/abitest/module_1/rust/src/lib.rs
  examples/aggregator/module/rust/src/lib.rs
  examples/chat/module/rust/src/lib.rs
  examples/injection/module/rust/src/lib.rs
  examples/trusted_database/module/rust/src/lib.rs
  sdk/rust/oak/src/grpc/client.rs
  sdk/rust/oak/src/grpc/mod.rs
  sdk/rust/oak/src/grpc/server.rs
  sdk/rust/oak/src/http/mod.rs
  sdk/rust/oak/src/io/mod.rs
  sdk/rust/oak/src/lib.rs
  sdk/rust/oak/src/logger/mod.rs
Labels: cla: yes

#1627 Make label mandatory on `oak::node_create`
  docs/programming-oak.md
  examples/abitest/module_0/rust/src/lib.rs
  examples/aggregator/module/rust/src/lib.rs
  examples/chat/module/rust/src/lib.rs
  examples/injection/module/rust/src/lib.rs
  examples/trusted_database/module/rust/src/lib.rs
  sdk/rust/oak/src/grpc/client.rs
  sdk/rust/oak/src/grpc/server.rs
  sdk/rust/oak/src/http/mod.rs
  sdk/rust/oak/src/lib.rs
  sdk/rust/oak/src/logger/mod.rs
Labels: cla: yes

#1628 Remove cargo-deny warnings for wildcard versions
  examples/deny.toml
  experimental/deny.toml
  oak_abi/deny.toml
  oak_client/deny.toml
  oak_derive/deny.toml
  oak_io/deny.toml
  oak_loader/deny.toml
  oak_runtime/deny.toml
  oak_services/deny.toml
  oak_sign/deny.toml
  oak_utils/deny.toml
  runner/deny.toml
  sdk/deny.toml
Labels: cla: yes

#1629 Resolve additional cargo-deny warnings
  examples/deny.toml
  experimental/deny.toml
  oak_loader/deny.toml
  oak_runtime/deny.toml
  oak_sign/deny.toml
  runner/deny.toml
  sdk/deny.toml
Labels: cla: yes

#1638 Implement Iterator for Receiver
  docs/programming-oak.md
  examples/abitest/module_0/rust/src/lib.rs
  examples/aggregator/module/rust/src/lib.rs
  examples/chat/module/rust/src/lib.rs
  examples/hello_world/module/rust/src/lib.rs
  examples/http_server/module/src/lib.rs
  examples/injection/module/rust/src/lib.rs
  examples/machine_learning/module/rust/src/lib.rs
  examples/private_set_intersection/module/rust/src/lib.rs
  examples/running_average/module/rust/src/lib.rs
  examples/translator/module/rust/src/lib.rs
  examples/trusted_database/module/rust/src/handler.rs
  examples/trusted_database/module/rust/src/lib.rs
  sdk/rust/oak/src/io/receiver.rs
  sdk/rust/oak/src/lib.rs
Labels: cla: yes

#1632 Add `name` to `channel_create`
  docs/abi.md
  docs/programming-oak.md
  examples/abitest/module_0/rust/src/lib.rs
  examples/abitest/module_1/rust/src/lib.rs
  examples/aggregator/client/cpp/aggregator.cc
  examples/aggregator/module/rust/src/lib.rs
  examples/aggregator/oak_app_manifest.toml
  examples/chat/module/rust/src/lib.rs
  examples/injection/module/rust/src/lib.rs
  examples/private_set_intersection/oak_app_manifest.toml
  examples/private_set_intersection/private_set_intersection.sign
  examples/trusted_database/module/rust/src/lib.rs
  experimental/web/index.html
  oak/module/oak_abi.h
  oak/module/oak_main.h
  oak_abi/src/lib.rs
  oak_runtime/introspection_browser_client/components/Event/index.tsx
  oak_runtime/introspection_browser_client/components/Root/index.tsx
  oak_runtime/src/channel.rs
  oak_runtime/src/lib.rs
  oak_runtime/src/node/grpc/server/mod.rs
  oak_runtime/src/node/http/mod.rs
  oak_runtime/src/node/http/tests.rs
  oak_runtime/src/node/wasm/mod.rs
  oak_runtime/src/node/wasm/tests.rs
  oak_runtime/src/proxy.rs
  oak_runtime/src/tests.rs
  proto/introspection_events.proto
  sdk/rust/oak/src/grpc/client.rs
  sdk/rust/oak/src/grpc/mod.rs
  sdk/rust/oak/src/grpc/server.rs
  sdk/rust/oak/src/http/mod.rs
  sdk/rust/oak/src/io/mod.rs
  sdk/rust/oak/src/lib.rs
  sdk/rust/oak/src/logger/mod.rs
  sdk/rust/oak/src/stubs.rs
Labels: cla: yes

#1637 Implement Decodable and Encodable for Either type
  examples/Cargo.lock
  experimental/Cargo.lock
  oak_derive/Cargo.lock
  oak_io/Cargo.lock
  oak_io/Cargo.toml
  oak_io/src/lib.rs
  oak_loader/Cargo.lock
  oak_runtime/Cargo.lock
  oak_services/Cargo.lock
  sdk/Cargo.lock
Labels: cla: yes

#1641 Install `rust-analyzer` in docker image
  .devcontainer.json
  Dockerfile
Labels: cla: yes

#1625 Refactor oak sign key pair
  examples/Cargo.lock
  examples/chat/module/rust/tests/integration_test.rs
  experimental/Cargo.lock
  oak_loader/Cargo.lock
  oak_runtime/Cargo.lock
  oak_sign/Cargo.lock
  oak_sign/Cargo.toml
  oak_sign/src/lib.rs
  oak_sign/src/main.rs
  oak_sign/src/tests.rs
  sdk/Cargo.lock
Labels: cla: yes

#1643 Add git clean script that preserves auth files
  scripts/git_clean
Labels: cla: yes

#1633 Add top privilege tag
  oak_abi/proto/label.proto
  oak_abi/src/label/mod.rs
  oak_runtime/src/lib.rs
  oak_runtime/src/node/grpc/server/mod.rs
  oak_runtime/src/node/http/mod.rs
  oak_runtime/src/tests.rs
Labels: cla: yes

#1647 Use Either pattern to initialize aggregator node
  examples/Cargo.lock
  examples/aggregator/module/rust/Cargo.toml
  examples/aggregator/module/rust/src/lib.rs
  examples/aggregator/proto/aggregator_init.proto
Labels: cla: yes

#1645 Show channel name in the dynamic introspection graph
  oak_runtime/introspection_browser_client/components/StateGraph/index.tsx
Labels: cla: yes, lang/JavaScript

#1653 Implement planner + router + worker pattern
  examples/chat/module/rust/src/lib.rs
  examples/chat/module/rust/tests/integration_test.rs
  examples/chat/oak_app_manifest.toml
  sdk/rust/oak/src/lib.rs
Labels: cla: yes

#1648 Move `name` out of node configuration proto
  docs/abi.md
  docs/programming-oak.md
  examples/abitest/module_0/rust/src/lib.rs
  examples/aggregator/client/cpp/aggregator.cc
  examples/aggregator/module/rust/src/lib.rs
  examples/aggregator/oak_app_manifest.toml
  examples/chat/module/rust/src/lib.rs
  examples/hello_world/module/rust/src/lib.rs
  examples/injection/module/rust/src/lib.rs
  examples/private_set_intersection/oak_app_manifest.toml
  examples/private_set_intersection/private_set_intersection.sign
  examples/trusted_database/module/rust/src/lib.rs
  experimental/web/index.html
  oak/module/oak_abi.h
  oak/module/oak_main.h
  oak_abi/proto/application.proto
  oak_abi/src/lib.rs
  oak_runtime/src/lib.rs
  oak_runtime/src/node/http/tests.rs
  oak_runtime/src/node/mod.rs
  oak_runtime/src/node/wasm/mod.rs
  oak_runtime/src/node/wasm/tests.rs
  oak_runtime/src/proxy.rs
  oak_runtime/src/tests.rs
  oak_runtime/tests/integration_test.rs
  sdk/rust/oak/src/grpc/client.rs
  sdk/rust/oak/src/grpc/server.rs
  sdk/rust/oak/src/http/mod.rs
  sdk/rust/oak/src/lib.rs
  sdk/rust/oak/src/logger/mod.rs
  sdk/rust/oak/src/node_config.rs
  sdk/rust/oak/src/roughtime/mod.rs
  sdk/rust/oak/src/storage/mod.rs
  sdk/rust/oak/src/stubs.rs
  sdk/rust/oak_app_build/src/main.rs
  sdk/rust/oak_tests/src/lib.rs
Labels: cla: yes

#1654 Add node name to `node_create` call
  examples/chat/module/rust/src/lib.rs
Labels: cla: yes

#1642 Amend definitions of labeled things.
  experimental/ni_coq/vfiles/EvAugSemantics.v
  experimental/ni_coq/vfiles/Events.v
  experimental/ni_coq/vfiles/GenericMap.v
  experimental/ni_coq/vfiles/LowEquivalences.v
  experimental/ni_coq/vfiles/NIUtilTheorems.v
  experimental/ni_coq/vfiles/PossibilisticNI.v
  experimental/ni_coq/vfiles/RuntimeModel.v
  experimental/ni_coq/vfiles/Unwind.v
Labels: cla: yes

#1651 Add label to ReceiverExt and SenderExt in the runtime
  oak_runtime/src/io.rs
  oak_runtime/src/lib.rs
  oak_runtime/src/proxy.rs
Labels: cla: yes

#1591 Async service generator
  experimental/oak_async/src/grpc.rs
  experimental/oak_async/src/io.rs
  experimental/oak_async/src/lib.rs
  oak_utils/src/lib.rs
Labels: cla: yes

#1635 Add an HTTP test with non-empty label
  examples/abitest/client/cpp/httptest.cc
  oak_runtime/src/node/http/mod.rs
  oak_runtime/src/node/http/tests.rs
Labels: cla: yes

#1657 Make command an associated type of CommandHandler
  examples/chat/module/rust/src/lib.rs
  examples/http_server/module/src/lib.rs
  examples/injection/module/rust/src/lib.rs
  examples/trusted_database/module/rust/src/lib.rs
  sdk/rust/oak/src/grpc/mod.rs
  sdk/rust/oak/src/lib.rs
Labels: cla: yes
