Repository project-oak/oak, pull requests merged in 2020-06, with the labels that each got.

#1050 runtime: drop now-unused oak_glue crate
  Cargo.lock
  Cargo.toml
  oak/server/rust/oak_glue/Cargo.toml
  oak/server/rust/oak_glue/oak_glue.h
  oak/server/rust/oak_glue/src/lib.rs
Labels: cla: yes

#1042 Generate docs for the `oak_abi` crate
  scripts/build_gh_pages
  scripts/check_docs
Labels: cla: yes

#1053 Replace simple_logger with env_logger
  Cargo.lock
  docs/programming-oak.md
  examples/abitest/tests/Cargo.toml
  examples/abitest/tests/src/tests.rs
  examples/aggregator/module/rust/Cargo.toml
  examples/aggregator/module/rust/src/tests.rs
  examples/hello_world/module/rust/Cargo.toml
  examples/hello_world/module/rust/src/tests.rs
  examples/private_set_intersection/module/rust/Cargo.toml
  examples/private_set_intersection/module/rust/src/tests.rs
  examples/running_average/module/rust/Cargo.toml
  examples/running_average/module/rust/src/tests.rs
  examples/translator/module/rust/Cargo.toml
  examples/translator/module/rust/src/tests.rs
  oak/server/rust/oak_loader/Cargo.toml
  oak/server/rust/oak_loader/src/main.rs
Labels: cla: yes

#1045 Make examples a separate workspace
  Cargo.lock
  Cargo.toml
  cloudbuild.yaml
  examples/Cargo.lock
  examples/Cargo.toml
  scripts/build_example
Labels: WIP, cla: yes

#1060 Update cargo lock
  examples/Cargo.lock
Labels: cla: yes

#1051 Support background steps in runner
  Cargo.lock
  runner/Cargo.toml
  runner/src/internal.rs
  runner/src/main.rs
Labels: cla: yes

#1062 docs: update for new generated doc location
  docs/programming-oak.md
  docs/sdk.md
Labels: cla: yes

#1063 Move experimental crates to a separate workspace
  Cargo.lock
  Cargo.toml
  cloudbuild.yaml
  experimental/Cargo.lock
  experimental/Cargo.toml
  scripts/build_experimental
  scripts/check_formatting
  scripts/format
Labels: cla: yes

#1049 Add Trusted Information Retrieval example
  examples/Cargo.lock
  examples/Cargo.toml
  examples/trusted_information_retrieval/client/BUILD
  examples/trusted_information_retrieval/client/trusted_information_retrieval.cc
  examples/trusted_information_retrieval/config/BUILD
  examples/trusted_information_retrieval/config/config.textproto
  examples/trusted_information_retrieval/database.xml
  examples/trusted_information_retrieval/module/rust/Cargo.toml
  examples/trusted_information_retrieval/module/rust/build.rs
  examples/trusted_information_retrieval/module/rust/src/database.rs
  examples/trusted_information_retrieval/module/rust/src/lib.rs
  examples/trusted_information_retrieval/module/rust/src/tests.rs
  examples/trusted_information_retrieval/proto/BUILD
  examples/trusted_information_retrieval/proto/trusted_information_retrieval.proto
  examples/trusted_information_retrieval/server/BUILD
  oak/server/rust/oak_loader/src/main.rs
  scripts/run_examples
  scripts/run_server
Labels: cla: yes

#1068 Propagate gRPC request label
  docs/programming-oak.md
  examples/abitest/client/abitest.cc
  examples/aggregator/client/aggregator.cc
  examples/aggregator/client/android/cpp/client.cc
  examples/chat/client/chat.cc
  examples/hello_world/client/hello_world.cc
  examples/hello_world/client/nodejs/index.js
  examples/machine_learning/client/machine_learning.cc
  examples/private_set_intersection/client/private_set_intersection.cc
  examples/running_average/client/running_average.cc
  examples/tensorflow/client/tensorflow.cc
  examples/translator/client/translator.go
  oak/client/application_client.h
  oak/common/label.cc
  oak/common/label.h
  oak/server/rust/oak_runtime/src/node/grpc/server/mod.rs
  oak/server/rust/oak_runtime/src/runtime/mod.rs
  sdk/rust/oak/src/lib.rs
Labels: cla: yes

#1073 Use labels in TIR
  examples/trusted_information_retrieval/client/trusted_information_retrieval.cc
Labels: cla: yes

#1070 Grant privilege to WebAssembly nodes
  Cargo.lock
  examples/Cargo.lock
  oak/common/label.cc
  oak/common/label.h
  oak/proto/label.proto
  oak/server/rust/oak_runtime/Cargo.toml
  oak/server/rust/oak_runtime/src/node/mod.rs
  oak/server/rust/oak_runtime/src/node/wasm/mod.rs
  oak/server/rust/oak_runtime/src/runtime/mod.rs
  oak/server/rust/oak_runtime/src/runtime/tests.rs
  oak_abi/src/label/mod.rs
Labels: cla: yes

#1047 Add Rust Roughtime client
  Cargo.lock
  WORKSPACE
  examples/Cargo.lock
  examples/Cargo.toml
  oak/server/rust/oak_runtime/Cargo.toml
  oak/server/rust/oak_runtime/src/lib.rs
  oak/server/rust/oak_runtime/src/time/mod.rs
  oak/server/rust/oak_runtime/src/time/tests.rs
  oak/server/rust/oak_runtime/tests/integration_test.rs
  oak/server/time/BUILD
  oak/server/time/roughtime_client.cc
  oak/server/time/roughtime_client.h
  oak/server/time/roughtime_client_test.cc
  oak/server/time/roughtime_util.cc
  oak/server/time/roughtime_util.h
  oak/server/time/roughtime_util_test.cc
  third_party/roughenough/src/client.rs
  third_party/roughenough/src/error.rs
  third_party/roughtime/BUILD
  third_party/roughtime/roughtime.BUILD
Labels: cla: yes

#1076 examples: drop rustfmt example
  docs/programming-oak.md
  examples/Cargo.lock
  examples/Cargo.toml
  examples/rustfmt/client/BUILD
  examples/rustfmt/client/rustfmt.cc
  examples/rustfmt/config/BUILD
  examples/rustfmt/config/config.textproto
  examples/rustfmt/module/rust/Cargo.toml
  examples/rustfmt/module/rust/build.rs
  examples/rustfmt/module/rust/src/lib.rs
  examples/rustfmt/proto/BUILD
  examples/rustfmt/proto/rustfmt.proto
  scripts/build_examples
  scripts/run_examples
Labels: cla: yes

#1064 Update scripts after reorganization of the code
  examples/Cargo.lock
  examples/trusted_information_retrieval/module/rust/src/database.rs
  examples/trusted_information_retrieval/module/rust/src/lib.rs
  examples/trusted_information_retrieval/module/rust/src/tests.rs
  scripts/check_cargo_deny
  scripts/check_formatting
  scripts/common
  scripts/format
  scripts/run_tests
  third_party/expect/Cargo.toml
Labels: cla: yes

#1080 More accurate logging of gRPC requests lifecycle
  examples/aggregator/client/aggregator.cc
  sdk/rust/oak/src/grpc/mod.rs
  sdk/rust/oak/src/lib.rs
Labels: cla: yes

#1077 Pass additional args to aggregator example
  examples/aggregator/client/aggregator.cc
  scripts/run_example
Labels: cla: yes

#1092 Add sha256 value back to io_grpc_grpc_java
  WORKSPACE
Labels: cla: yes

#1090 Check markdown links
  Dockerfile
  docs/PULL_REQUEST_TEMPLATE.md
  docs/abi.md
  docs/concepts.md
  docs/sdk.md
  examples/aggregator/README.md
  scripts/check_formatting
Labels: cla: yes

#1083 Time the commands in run_tests and run_tests_tsan
  scripts/run_tests
  scripts/run_tests_tsan
Labels: cla: yes

#1096 Install node deps when building an example
  scripts/build_example
Labels: cla: yes

#1084 Improve logging of gRPC request handling
  oak/server/rust/oak_runtime/src/node/grpc/server/mod.rs
Labels: cla: yes

#1103 Revert "Install node deps when building an example"
  scripts/build_example
Labels: cla: yes

#1095 Fix up translator example
  WORKSPACE
  docs/programming-oak.md
  examples/translator/client/BUILD
  examples/translator/client/translator.go
  oak/proto/BUILD
Labels: cla: yes

#1107 Log errors caused by running gRPC server
  oak/server/rust/oak_runtime/src/node/grpc/server/mod.rs
Labels: cla: yes

#1106 Split runtime/mod.rs and shuffle logging around
  oak/server/rust/oak_runtime/src/message.rs
  oak/server/rust/oak_runtime/src/node/wasm/mod.rs
  oak/server/rust/oak_runtime/src/runtime/mod.rs
  oak/server/rust/oak_runtime/src/runtime/proxy.rs
Labels: cla: yes

#1099 Node: Exit with code 1 if an error occured
  examples/hello_world/client/nodejs/index.js
Labels: cla: yes

#1094 Clean up log warnings and errors
  oak/server/rust/oak_runtime/src/node/grpc/client.rs
  oak/server/rust/oak_runtime/src/node/logger.rs
  oak/server/rust/oak_runtime/src/runtime/mod.rs
Labels: cla: yes

#1086 Implement Roughtime client pseudo-node
  examples/abitest/module_0/rust/src/lib.rs
  oak/proto/BUILD
  oak/proto/application.proto
  oak/proto/roughtime_service.proto
  oak/server/rust/oak_runtime/src/node/grpc/mod.rs
  oak/server/rust/oak_runtime/src/node/mod.rs
  oak/server/rust/oak_runtime/src/node/roughtime.rs
  oak/server/rust/oak_runtime/src/time/mod.rs
  oak_abi/build.rs
  oak_abi/src/proto/mod.rs
  oak_utils/src/lib.rs
  runner/src/main.rs
  scripts/run_example
  sdk/rust/oak/src/roughtime/mod.rs
Labels: cla: yes

#1115 Use `anyhow` for error handling in oak_loader
  oak/server/rust/oak_loader/src/main.rs
  oak_abi/src/lib.rs
Labels: cla: yes

#1110 Add Rust client for Trusted Information Retrieval
  cloudbuild.yaml
  docs/programming-oak.md
  examples/Cargo.lock
  examples/Cargo.toml
  examples/trusted_information_retrieval/client/rust/Cargo.toml
  examples/trusted_information_retrieval/client/rust/build.rs
  examples/trusted_information_retrieval/client/rust/src/main.rs
  examples/trusted_information_retrieval/client/trusted_information_retrieval.cc
  scripts/build_example
  scripts/build_examples
  scripts/run_example
  scripts/run_examples
  scripts/run_server
Labels: cla: yes

#1123 Make wait_on_channels errors more consistent
  examples/abitest/module_0/rust/src/lib.rs
  oak/server/rust/oak_runtime/src/node/wasm/mod.rs
Labels: cla: yes

#1111 docs: explicitly mention need for musl
  docs/development.md
Labels: cla: yes

#1119 Do not format code in node_modules
  scripts/check_formatting
  scripts/format
Labels: cla: yes

#1114 Return ChannelReadStatus from Receiver::wait
  oak/server/rust/oak_runtime/src/node/wasm/mod.rs
  oak/server/rust/oak_runtime/src/runtime/mod.rs
  sdk/rust/oak/src/io/receiver.rs
  sdk/rust/oak/src/lib.rs
Labels: cla: yes

#1131 Use error instead of panic
  sdk/rust/oak/src/io/receiver.rs
  sdk/rust/oak/src/lib.rs
Labels: cla: yes

#1138 Update links to docs on GitHub
  docs/programming-oak.md
  docs/sdk.md
Labels: cla: yes

#1135 Add support for format and CI steps in runner
  .dockerignore
  runner/src/internal.rs
  runner/src/main.rs
  scripts/runner
Labels: cla: yes

#1142 Add support for Node.js clients to the run_example script
  examples/hello_world/client/nodejs/README.MD
  scripts/build_example
  scripts/run_example
Labels: cla: yes

#1140 Add label support to the nodejs client
  examples/hello_world/client/nodejs/index.js
  examples/hello_world/client/nodejs/package-lock.json
  examples/hello_world/client/nodejs/package.json
Labels: cla: yes

#1146 Replace incorrect command in Node.js Client ReadMe
  examples/hello_world/client/nodejs/README.MD
Labels: cla: yes

#1147 Run the hello world nodejs client in our CI
  cloudbuild.yaml
Labels: cla: yes

#1150 abitest: re-enable server streaming tests
  examples/abitest/example.toml
Labels: cla: yes

#1148 Allow specifying multiple clients for run_examples
  cloudbuild.yaml
  scripts/run_example
  scripts/run_examples
Labels: cla: yes

#1153 docs: describe config map use
  docs/abi.md
  docs/programming-oak.md
Labels: cla: yes

#1141 Add trusted CA certs to Oak runtime
  .gitignore
  cloudbuild.yaml
  oak/server/rust/oak_loader/src/certs/README.md
  oak/server/rust/oak_loader/src/certs/roots.pem
  oak/server/rust/oak_loader/src/main.rs
  scripts/generate_root_ca_certs
Labels: cla: yes

#1139 Move top-level Cargo.toml to oak/server
  BUILD
  examples/aggregator/README.md
  examples/aggregator/scripts/run_backend
  examples/aggregator/scripts/run_server
  examples/aggregator/server/BUILD
  examples/authentication/README.md
  examples/hello_world/gcp/BUILD
  examples/hello_world/gcp/config.json
  oak/server/BUILD
  oak/server/Cargo.lock
  oak/server/Cargo.toml
  oak/server/rust/oak_loader/src/main.rs
  runner/src/main.rs
  scripts/build_example
  scripts/build_gh_pages
  scripts/check_docs
  scripts/common
  scripts/deploy_example_gcp
  scripts/run_server
Labels: cla: yes

#1160 Update path to oak_loader in build_reproducibility_index
  scripts/build_reproducibility_index
Labels: cla: yes

#1149 Integrate the Node.js client with the rust runner
  examples/hello_world/example.toml
  runner/src/main.rs
Labels: cla: yes, lang/Rust

#1157 Rename master branch to main
  .github/workflows/build_rust_docs.yaml
  .github/workflows/reproducibility.yaml
  docs/CONTRIBUTING.md
  docs/programming-oak.md
  oak/server/rust/oak_runtime/src/node/wasm/mod.rs
  oak/server/rust/oak_runtime/src/runtime/channel.rs
  oak/server/rust/oak_runtime/src/runtime/mod.rs
  oak_abi/src/label/mod.rs
  sdk/rust/oak/src/lib.rs
Labels: cla: yes

#1161 Update Rust dependencies for Oak runtime
  examples/Cargo.lock
  oak/server/Cargo.lock
  oak/server/rust/oak_runtime/src/node/wasm/mod.rs
  sdk/Cargo.lock
Labels: cla: yes

#1164 Drop patch for wabt, no longer used
  third_party/wabt/BUILD
  third_party/wabt/LICENSE
  third_party/wabt/config.h.patch
  third_party/wabt/wabt.BUILD
Labels: cla: yes

#1158 Support rust toolchain override in `runner`
  oak/server/rust/oak_runtime/Cargo.toml
  runner/src/internal.rs
  runner/src/main.rs
Labels: cla: yes

#1152 Add an external database to TIR example
  examples/Cargo.lock
  examples/Cargo.toml
  examples/trusted_information_retrieval/backend/Cargo.toml
  examples/trusted_information_retrieval/backend/build.rs
  examples/trusted_information_retrieval/backend/src/database.rs
  examples/trusted_information_retrieval/backend/src/main.rs
  examples/trusted_information_retrieval/backend/src/tests.rs
  examples/trusted_information_retrieval/config/config.toml
  examples/trusted_information_retrieval/module/rust/Cargo.toml
  examples/trusted_information_retrieval/module/rust/src/config.rs
  examples/trusted_information_retrieval/module/rust/src/database.rs
  examples/trusted_information_retrieval/module/rust/src/lib.rs
  examples/trusted_information_retrieval/module/rust/src/tests.rs
  examples/trusted_information_retrieval/module/rust/tests/integration_test.rs
  examples/trusted_information_retrieval/proto/trusted_information_retrieval.proto
  oak_utils/src/lib.rs
  scripts/build_example
  scripts/run_example
  scripts/run_server
Labels: cla: yes

#1169 Fix incorrect example client checks
  scripts/run_example
Labels: bug, cla: yes

#1171 Add json for Aggregator's monitoring dashboard
  examples/aggregator/README.md
  examples/aggregator/gcp/aggregator-dashboard.json
Labels: cla: yes

#1172 Add grpc streaming metrics
  examples/aggregator/README.md
  oak/server/rust/oak_runtime/src/metrics/mod.rs
  oak/server/rust/oak_runtime/src/node/grpc/server/mod.rs
Labels: cla: yes

#1170 Build scripts: Name client variants by their build system for clarity
  cloudbuild.yaml
  examples/hello_world/client/nodejs/README.MD
  scripts/build_example
  scripts/run_example
  scripts/run_examples
Labels: cla: yes

#1180 Make client actually fail on errors
  examples/trusted_information_retrieval/client/trusted_information_retrieval.cc
Labels: cla: yes

#1181 third_party: drop now-unused code from Asylo
  third_party/asylo/BUILD
  third_party/asylo/cleansing_allocator.h
  third_party/asylo/cleansing_types.h
  third_party/asylo/status_macros.h
Labels: WIP, cla: yes

#1174 Add instructions for programatically creating alert policies
  examples/aggregator/README.md
  examples/aggregator/gcp/aggregator-alert-policy.json
  examples/aggregator/scripts/monitoring
Labels: cla: yes

#1179 Specify build target for backend components in examples
  BUILD
  examples/aggregator/server/BUILD
  scripts/build_example
  scripts/run_example
Labels: cla: yes

#1184 Update README for aggregator
  examples/aggregator/README.md
Labels: cla: yes

#1185 Docs: Clarify that Channels and Nodes each only have one Label
  docs/concepts.md
Labels: cla: yes

#1176 Always run all clients in run_examples
  cloudbuild.yaml
  scripts/run_example
  scripts/run_examples
Labels: cla: yes

#1175 Move NPM build step inside of client variant logic inside of build_example
  scripts/build_example
  scripts/run_example
Labels: cla: yes

#1196 Add simple integration with cargo-crev
  Dockerfile
  cloudbuild.yaml
  scripts/run_cargo_crev
Labels: cla: yes

#1191 Add workaround for aarch64 Rust missing symbols
  .cargo/config
Labels: cla: yes

#1209 scripts: suppress ThreadSanitizer report on shutdown
  .tsan_suppress
  scripts/run_tests_tsan
Labels: cla: yes

#1203 Docs: Verbosify IFC example to increase clarity
  docs/concepts.md
Labels: cla: yes

#1211 Downgrade error on gRPC client node invocation channel closure
  oak/server/rust/oak_runtime/src/io.rs
  oak/server/rust/oak_runtime/src/node/grpc/client.rs
Labels: cla: yes

#1188 Build coverage information from abitest run
  .github/workflows/upload_coverage.yaml
  Dockerfile
  scripts/run_tests_coverage
Labels: cla: yes

#1193 Use the default target for backend components
  scripts/build_example
  scripts/common
  scripts/run_example
Labels: cla: yes

#1167 Only allow public Nodes to create entities
  docs/abi.md
  docs/concepts.md
  oak/server/rust/oak_runtime/src/message.rs
  oak/server/rust/oak_runtime/src/runtime/mod.rs
  oak/server/rust/oak_runtime/src/runtime/tests.rs
Labels: cla: yes

#1217 Use brackets in bash variables
  scripts/build_example
  scripts/run_example
Labels: cla: yes

#990 Add mailing list and slack links to text body
  README.md
Labels: cla: yes
