Repository project-oak/oak, pull requests merged in 2020-09, with the labels that each got.

#1409 Ensure NodeCreated is fired for the initial node
  oak_runtime/src/lib.rs
Labels: cla: yes

#1398 Add support for IFC labels as json
  examples/Cargo.lock
  examples/http_server/client/Cargo.toml
  examples/http_server/client/client
  examples/http_server/client/src/main.rs
  examples/http_server/example.toml
  oak_abi/Cargo.lock
  oak_abi/Cargo.toml
  oak_io/Cargo.lock
  oak_loader/Cargo.lock
  oak_runtime/Cargo.lock
  oak_runtime/src/node/http/mod.rs
  oak_runtime/src/node/http/tests.rs
  oak_services/Cargo.lock
  oak_utils/src/lib.rs
  sdk/Cargo.lock
Labels: cla: yes

#1405 Runner: Remove invalid CLI flag
  runner/src/main.rs
Labels: cla: yes

#1415 Format JavaScript & TypeScript with prettier
  examples/hello_world/client/nodejs/index.js
  runner/src/main.rs
Labels: cla: yes

#1403 Proofs of Lemmas in TraceTheorems.v
  experimental/ni_coq/vfiles/TraceTheorems.v
Labels: cla: yes

#1416 Create dependabot configuration
  .github/dependabot.yml
Labels: cla: yes

#1333 Put --logs in the right place
  docs/development.md
Labels: cla: yes

#1373 Add arm64v8 Dockerfile
  arm64v8.Dockerfile
Labels: cla: yes, platform/aarch64

#1382 Bundle & serve skeleton introspection browser client
  oak_loader/Cargo.toml
  oak_runtime/Cargo.toml
  oak_runtime/src/introspect.rs
  oak_runtime/src/introspection_browser_client/.gitignore
  oak_runtime/src/introspection_browser_client/build
  oak_runtime/src/introspection_browser_client/package-lock.json
  oak_runtime/src/introspection_browser_client/package.json
  runner/src/main.rs
Labels: cla: yes

#1427 Add basic TypeScript introspection client
  oak_runtime/introspection_browser_client/.gitignore
  oak_runtime/introspection_browser_client/build
  oak_runtime/introspection_browser_client/index.tsx
  oak_runtime/introspection_browser_client/package-lock.json
  oak_runtime/introspection_browser_client/package.json
  oak_runtime/introspection_browser_client/static/index.html
  oak_runtime/introspection_browser_client/tsconfig.json
  oak_runtime/introspection_browser_client/webpack.config.js
  oak_runtime/src/introspect.rs
  oak_runtime/src/introspection_browser_client/.gitignore
  oak_runtime/src/introspection_browser_client/build
  oak_runtime/src/introspection_browser_client/package-lock.json
  oak_runtime/src/introspection_browser_client/package.json
  runner/src/main.rs
Labels: cla: yes

#1429 Possibilistic single-step for system transition
  experimental/ni_coq/vfiles/EvAugSemantics.v
  experimental/ni_coq/vfiles/Parameters.v
  experimental/ni_coq/vfiles/PossibilisticNI.v
  experimental/ni_coq/vfiles/RuntimeModel.v
  experimental/ni_coq/vfiles/TraceTheorems.v
Labels: cla: yes

#1426 Allow both JSON and protobuf labels in HTTP requests
  examples/http_server/client/src/main.rs
  oak_abi/src/lib.rs
  oak_runtime/src/node/http/mod.rs
  oak_runtime/src/node/http/tests.rs
Labels: cla: yes

#1432 Introspection client: Get state from events
  oak_runtime/introspection_browser_client/index.tsx
  oak_runtime/introspection_browser_client/tsconfig.json
Labels: cla: yes

#1438 Exclude protoc generated files from formatting
  FORCE_CI
  oak_runtime/introspection_browser_client/.gitignore
  oak_runtime/introspection_browser_client/build
  oak_runtime/introspection_browser_client/index.tsx
  runner/src/main.rs
Labels: cla: yes

#1404 Use protos for Invocations
  examples/aggregator/client/aggregator.cc
  examples/aggregator/oak_app_manifest.toml
  examples/trusted_information_retrieval/oak_app_manifest.toml
  oak/module/oak_main.h
  oak_io/src/handle.rs
  oak_runtime/build.rs
  oak_runtime/src/node/grpc/invocation.rs
  oak_runtime/src/node/grpc/server/mod.rs
  oak_runtime/src/node/http/mod.rs
  oak_runtime/src/node/http/tests.rs
  oak_runtime/src/proto/mod.rs
  oak_services/build.rs
  oak_services/proto/grpc_invocation.proto
  oak_services/proto/http_encap.proto
  oak_services/proto/http_invocation.proto
  oak_services/src/proto/mod.rs
  sdk/rust/oak/build.rs
  sdk/rust/oak/src/grpc/mod.rs
  sdk/rust/oak/src/grpc/server.rs
  sdk/rust/oak/src/http/mod.rs
  sdk/rust/oak/src/invocations.rs
  sdk/rust/oak/src/lib.rs
Labels: cla: yes

#1439 Refactor introspection client into components for clarity
  oak_runtime/introspection_browser_client/components/ApplicationStateOverview/index.tsx
  oak_runtime/introspection_browser_client/components/EventList/index.tsx
  oak_runtime/introspection_browser_client/components/Root/index.tsx
  oak_runtime/introspection_browser_client/index.tsx
  oak_runtime/introspection_browser_client/tsconfig.json
  oak_runtime/introspection_browser_client/webpack.config.js
Labels: cla: yes

#1442 Update prettier to version 2
  Dockerfile
  docs/programming-oak.md
  examples/hello_world/client/nodejs/index.js
  oak_runtime/introspection_browser_client/components/ApplicationStateOverview/index.tsx
  oak_runtime/introspection_browser_client/components/Root/index.tsx
  oak_runtime/introspection_browser_client/webpack.config.js
Labels: cla: yes

#1444 Formatting: Add webpack output to ignored files
  runner/src/main.rs
Labels: bug, cla: yes

#1441 Add Node name & ChannelHalf direction support to the introspection client
  oak_runtime/introspection_browser_client/components/ApplicationStateOverview/index.tsx
  oak_runtime/introspection_browser_client/components/Root/index.tsx
  oak_runtime/src/lib.rs
  proto/introspection_events.proto
Labels: cla: yes

#1447 Remove need for step_system_multi_backwards admit
  experimental/ni_coq/vfiles/EvAugSemantics.v
  experimental/ni_coq/vfiles/PossibilisticNI.v
  experimental/ni_coq/vfiles/TraceTheorems.v
Labels: cla: yes

#1448 add Coq artifacts to .gitignore
  .gitignore
Labels: cla: yes

#1449 Compress introspection client files with gzip
  oak_runtime/introspection_browser_client/package-lock.json
  oak_runtime/introspection_browser_client/package.json
  oak_runtime/introspection_browser_client/webpack.config.js
  oak_runtime/src/introspect.rs
Labels: cla: yes

#1446 Add labels to introspection events
  oak_runtime/introspection_browser_client/build
  oak_runtime/introspection_browser_client/components/ApplicationStateOverview/index.tsx
  oak_runtime/introspection_browser_client/components/EventList/index.tsx
  oak_runtime/introspection_browser_client/components/Root/index.tsx
  oak_runtime/src/lib.rs
  oak_runtime/src/proto/mod.rs
  proto/introspection_events.proto
Labels: cla: yes, lang/Rust

#1451 Render oakApplicationState with graphviz
  oak_runtime/introspection_browser_client/components/Root/index.tsx
  oak_runtime/introspection_browser_client/components/StateGraph/index.tsx
  oak_runtime/introspection_browser_client/package-lock.json
  oak_runtime/introspection_browser_client/package.json
  oak_runtime/introspection_browser_client/tsconfig.json
  oak_runtime/introspection_browser_client/webpack.config.js
  oak_runtime/src/introspect.rs
Labels: cla: yes

#1454 Fix protobuf silently losing precision for 64 bit integers in JS
  oak_runtime/introspection_browser_client/components/ApplicationStateOverview/index.tsx
  oak_runtime/introspection_browser_client/components/Root/index.tsx
  oak_runtime/introspection_browser_client/components/StateGraph/index.tsx
  proto/introspection_events.proto
Labels: cla: yes

#1443 Fix early termination of HTTP server node
  oak_runtime/src/node/http/mod.rs
  oak_runtime/src/node/http/tests.rs
Labels: cla: yes

#1455 Introspection: Add basic styles & navigation
  oak_runtime/introspection_browser_client/components/MainTabs/index.tsx
  oak_runtime/introspection_browser_client/components/Root/index.tsx
  oak_runtime/introspection_browser_client/components/StateGraph/index.tsx
  oak_runtime/introspection_browser_client/package-lock.json
  oak_runtime/introspection_browser_client/package.json
  oak_runtime/introspection_browser_client/static/index.html
Labels: cla: yes

#1392 Use signature label in Private Set Intersection
  examples/aggregator/client/aggregator.cc
  examples/private_set_intersection/client/private_set_intersection.cc
  examples/private_set_intersection/example.toml
  examples/private_set_intersection/oak_app_manifest.toml
  examples/private_set_intersection/private_set_intersection.sign
  examples/private_set_intersection/signatures.toml
  examples/trusted_information_retrieval/client/trusted_information_retrieval.cc
  examples/trusted_information_retrieval/example.toml
  examples/trusted_information_retrieval/signatures.toml
  oak/client/application_client.h
  oak/common/label.cc
  oak/common/label.h
  oak_runtime/src/lib.rs
  oak_runtime/src/node/wasm/mod.rs
  oak_runtime/src/node/wasm/tests.rs
Labels: cla: yes

#1461 Implement more comprehensive HTTP example
  examples/Cargo.lock
  examples/http_server/README.md
  examples/http_server/module/Cargo.toml
  examples/http_server/module/src/lib.rs
  examples/http_server/module/static/index.html
  oak_runtime/src/node/http/mod.rs
  oak_runtime/src/node/http/tests.rs
  oak_services/proto/http_encap.proto
Labels: cla: yes

#1463 Make http_server example client actually log
  examples/Cargo.lock
  examples/http_server/client/Cargo.toml
  examples/http_server/client/src/main.rs
Labels: cla: yes

#1460 Respond with bad request if oak-label is not set in HTTP request
  oak_runtime/src/node/http/mod.rs
Labels: cla: yes

#1457 Proof automation in TraceTheorems.v
  experimental/ni_coq/vfiles/TraceTheorems.v
Labels: cla: yes

#1391 [RFC] Async SDK
  rfcs/01391_async_sdk.md
Labels: RFC, cla: yes

#1468 Proof of unwinding for havoc call.
  experimental/ni_coq/vfiles/PossibilisticNI.v
  experimental/ni_coq/vfiles/RuntimeModel.v
Labels: cla: yes

#1479 Update vulnerable subdependency
  oak_runtime/introspection_browser_client/package-lock.json
Labels: cla: yes

#1484 Skip NPM installs if dependencies didn't change
  oak_runtime/introspection_browser_client/build
  oak_runtime/introspection_browser_client/package.json
  oak_runtime/introspection_browser_client/postinstall
Labels: cla: yes, lang/Shell

#1485 Preserve last modified date for generated proto code
  oak_runtime/introspection_browser_client/.gitignore
  oak_runtime/introspection_browser_client/build
Labels: cla: yes, lang/Shell

#1486 Cache TypeScript compilation
  oak_runtime/introspection_browser_client/package-lock.json
  oak_runtime/introspection_browser_client/package.json
  oak_runtime/introspection_browser_client/webpack.config.js
Labels: cla: yes

#1483 runtime: break down node count metric by type
  oak_runtime/src/lib.rs
  oak_runtime/src/metrics/mod.rs
  oak_runtime/src/node/grpc/client.rs
  oak_runtime/src/node/grpc/server/mod.rs
  oak_runtime/src/node/http/mod.rs
  oak_runtime/src/node/logger.rs
  oak_runtime/src/node/mod.rs
  oak_runtime/src/node/roughtime.rs
  oak_runtime/src/node/storage.rs
  oak_runtime/src/node/wasm/mod.rs
  oak_runtime/src/proxy.rs
  oak_runtime/src/tests.rs
  oak_runtime/tests/integration_test.rs
Labels: cla: yes

#1480 Runner tweaks
  runner/src/internal.rs
  runner/src/main.rs
  scripts/run_tests_coverage
Labels: cla: yes

#1487 Preserve last modified date for webpack output
  oak_runtime/introspection_browser_client/.gitignore
  oak_runtime/introspection_browser_client/build
  oak_runtime/introspection_browser_client/webpack.config.js
Labels: cla: yes, lang/Shell

#1469 Retry sending requests in HTTP tests to make the tests stable
  oak_runtime/src/node/http/tests.rs
Labels: cla: yes

#1490 Write call single-step, single-thread unwind
  experimental/ni_coq/Makefile.conf
  experimental/ni_coq/_CoqProject
  experimental/ni_coq/vfiles/LowEquivalences.v
  experimental/ni_coq/vfiles/NIUtilTheorems.v
  experimental/ni_coq/vfiles/PossibilisticNI.v
  experimental/ni_coq/vfiles/Unwind.v
Labels: cla: yes

#1493 Create Oak Chrome extension skeleton
  chrome_extension/README.md
  chrome_extension/background.js
  chrome_extension/content.js
  chrome_extension/manifest.json
Labels: cla: yes

#1494 Use the runtime to start the test HTTP server node
  oak_runtime/src/node/http/tests.rs
Labels: cla: yes

#1498 Split node creation logic into separate trait
  oak_runtime/src/introspect.rs
  oak_runtime/src/lib.rs
  oak_runtime/src/node/mod.rs
  oak_runtime/src/proxy.rs
Labels: cla: yes

#1500 Drop branch info from coverage data
  scripts/run_tests_coverage
Labels: cla: yes

#1503 Introspection: Add support for message events
  oak_runtime/introspection_browser_client/components/Root/index.tsx
Labels: cla: yes

#1508 Build without mathcomp-finmap installed
  experimental/ni_coq/README.md
  experimental/ni_coq/vfiles/Events.v
  experimental/ni_coq/vfiles/Unwind.v
Labels: cla: yes

#1505 Introspection: Patch incorrect event order in the Event List tab
  oak_runtime/introspection_browser_client/components/EventList/index.tsx
Labels: cla: yes

#1504 Introspection: Add basic support for messages to the state graph
  oak_runtime/introspection_browser_client/components/StateGraph/index.tsx
Labels: cla: yes

#1510 Move tactics into their own file and test them
  experimental/ni_coq/_CoqProject
  experimental/ni_coq/vfiles/Tactics.v
  experimental/ni_coq/vfiles/TraceTheorems.v
Labels: cla: yes

#1507 Ignore Coq-generated file Makefile.conf
  .gitignore
  experimental/ni_coq/Makefile.conf
Labels: cla: yes

#1506 Introspection: Merge the dev setup with the build script
  oak_runtime/introspection_browser_client/build
  oak_runtime/introspection_browser_client/package.json
  oak_runtime/introspection_browser_client/webpack.config.js
Labels: cla: yes, lang/Shell

#1514 Introspection Tabs: Add missing React keys
  oak_runtime/introspection_browser_client/components/MainTabs/index.tsx
Labels: cla: yes

#1511 Introspection: Add client-side routing
  oak_runtime/introspection_browser_client/components/ChannelDetails/index.tsx
  oak_runtime/introspection_browser_client/components/HandleDetails/index.tsx
  oak_runtime/introspection_browser_client/components/NodeDetails/index.tsx
  oak_runtime/introspection_browser_client/components/NotFound/index.tsx
  oak_runtime/introspection_browser_client/components/Root/index.tsx
  oak_runtime/introspection_browser_client/components/StateGraph/index.tsx
  oak_runtime/introspection_browser_client/package-lock.json
  oak_runtime/introspection_browser_client/package.json
  oak_runtime/introspection_browser_client/static/index.html
  oak_runtime/introspection_browser_client/webpack.config.js
  oak_runtime/src/introspect.rs
Labels: cla: yes

#1515 Semantically format Events
  oak_runtime/introspection_browser_client/components/Event/index.tsx
  oak_runtime/introspection_browser_client/components/EventList/index.tsx
Labels: cla: yes

#1517 Revert "LICENSE: fill in copyright placeholder (#967)"
  LICENSE
Labels: cla: yes

#1519 Move from BigInts to strings for simplicity
  oak_runtime/introspection_browser_client/components/ApplicationStateOverview/index.tsx
  oak_runtime/introspection_browser_client/components/ChannelDetails/index.tsx
  oak_runtime/introspection_browser_client/components/HandleDetails/index.tsx
  oak_runtime/introspection_browser_client/components/NodeDetails/index.tsx
  oak_runtime/introspection_browser_client/components/Root/index.tsx
  oak_runtime/introspection_browser_client/components/StateGraph/index.tsx
Labels: cla: yes, lang/JavaScript

#1513 Allow headers with multiple values
  examples/http_server/module/src/lib.rs
  oak_runtime/src/node/http/mod.rs
  oak_services/proto/http_encap.proto
Labels: cla: yes

#1518 Add oak_* libraries to doc generation
  proto/handle.proto
  scripts/build_gh_pages
  scripts/common
Labels: cla: yes

#1520 Restructure NI defs to use low projections. NI Proofs using low proj steps.
  experimental/ni_coq/_CoqProject
  experimental/ni_coq/vfiles/EvAugSemantics.v
  experimental/ni_coq/vfiles/Events.v
  experimental/ni_coq/vfiles/LowEquivalences.v
  experimental/ni_coq/vfiles/NIUtilTheorems.v
  experimental/ni_coq/vfiles/PossibilisticNI.v
  experimental/ni_coq/vfiles/RuntimeModel.v
  experimental/ni_coq/vfiles/TraceTheorems.v
  experimental/ni_coq/vfiles/Unwind.v
Labels: cla: yes

#1521 Coq CI
  .github/workflows/coq.yaml
  experimental/ni_coq/oak-ni-coq.opam
Labels: cla: yes

#1531 Move C++ example clients to cpp directories
  docs/programming-oak.md
  examples/Cargo.toml
  examples/abitest/client/cpp/BUILD
  examples/abitest/client/cpp/abitest.cc
  examples/abitest/client/cpp/grpc_test_server.cc
  examples/abitest/client/cpp/grpc_test_server.h
  examples/abitest/client/cpp/grpctest.cc
  examples/abitest/client/cpp/grpctest.h
  examples/abitest/example.toml
  examples/aggregator/README.md
  examples/aggregator/client/cpp/BUILD
  examples/aggregator/client/cpp/aggregator.cc
  examples/aggregator/example.toml
  examples/aggregator/scripts/run_client
  examples/chat/client/cpp/BUILD
  examples/chat/client/cpp/chat.cc
  examples/chat/example.toml
  examples/hello_world/client/cpp/BUILD
  examples/hello_world/client/cpp/hello_world.cc
  examples/hello_world/example.toml
  examples/http_server/client/rust/Cargo.toml
  examples/http_server/client/rust/src/main.rs
  examples/http_server/example.toml
  examples/injection/client/cpp/BUILD
  examples/injection/client/cpp/injection.cc
  examples/injection/example.toml
  examples/machine_learning/client/cpp/BUILD
  examples/machine_learning/client/cpp/machine_learning.cc
  examples/machine_learning/example.toml
  examples/private_set_intersection/client/cpp/BUILD
  examples/private_set_intersection/client/cpp/private_set_intersection.cc
  examples/private_set_intersection/example.toml
  examples/running_average/client/cpp/BUILD
  examples/running_average/client/cpp/running_average.cc
  examples/running_average/example.toml
  examples/tensorflow/client/cpp/BUILD
  examples/tensorflow/client/cpp/tensorflow.cc
  examples/tensorflow/example.toml
  examples/translator/client/go/BUILD
  examples/translator/client/go/translator.go
  examples/translator/example.toml
  examples/trusted_database/client/cpp/BUILD
  examples/trusted_database/client/cpp/trusted_database.cc
  examples/trusted_database/example.toml
  examples/trusted_information_retrieval/client/cpp/BUILD
  examples/trusted_information_retrieval/client/cpp/trusted_information_retrieval.cc
  examples/trusted_information_retrieval/example.toml
  oak/server/storage/BUILD
  oak_services/proto/http_encap.proto
  runner/src/main.rs
Labels: cla: yes

#1532 Add missing introspection event for channel_try_read_message
  oak_runtime/src/lib.rs
Labels: cla: yes, lang/Rust

#1533 Nflows case for low_proj_steps_implies_leq_step
  experimental/ni_coq/vfiles/GenericMap.v
  experimental/ni_coq/vfiles/NIUtilTheorems.v
  experimental/ni_coq/vfiles/PossibilisticNI.v
Labels: cla: yes

#1528 Use idiomatic HTTP types in the SDK
  examples/Cargo.lock
  examples/http_server/module/Cargo.toml
  examples/http_server/module/src/lib.rs
  oak_loader/Cargo.lock
  oak_runtime/Cargo.lock
  oak_runtime/src/node/http/mod.rs
  oak_runtime/src/node/http/tests.rs
  oak_services/Cargo.lock
  oak_services/Cargo.toml
  oak_services/proto/http_encap.proto
  oak_services/src/http/mod.rs
  oak_services/src/lib.rs
  sdk/Cargo.lock
  sdk/rust/oak/Cargo.toml
  sdk/rust/oak/src/http/mod.rs
Labels: cla: yes

#1464 Add PSI Rust client
  examples/Cargo.lock
  examples/Cargo.toml
  examples/private_set_intersection/client/rust/Cargo.toml
  examples/private_set_intersection/client/rust/build.rs
  examples/private_set_intersection/client/rust/src/lib.rs
  examples/private_set_intersection/client/rust/src/main.rs
  examples/private_set_intersection/example.toml
Labels: cla: yes
