Repository project-oak/oak, pull requests merged in 2020-05, with the labels that each got.

#929 Configure shell to use rustup command before using it
  INSTALL.md
Labels: cla: yes, documentation

#930 Compile Docker server with clang
  cloudbuild.yaml
  scripts/build_example
Labels: cla: yes

#928 Track reproducibility index history
  .github/workflows/build_rust_docs.yaml
  .github/workflows/reproducibility.yaml
Labels: cla: yes

#926 Fix `ring` compilation errors in Bazel
  cargo/Cargo.toml
  cargo/remote/ring-0.16.12.BUILD
  oak/server/rust/oak_abi/Cargo.toml
  oak/server/rust/oak_glue/Cargo.toml
  oak/server/rust/oak_runtime/Cargo.toml
  scripts/cargo_raze
  scripts/run_clang_tidy
  scripts/run_tests
Labels: cla: yes

#938 Chat example: Update outdated app_address flag
  examples/chat/README.md
  examples/chat/client/chat.cc
Labels: cla: yes

#931 Add musl-tools to INSTALL.md
  INSTALL.md
Labels: cla: yes

#939 Free up space in reproducibility GitHub action
  .github/workflows/reproducibility.yaml
Labels: cla: yes

#943 Disable asan and tsan
  cloudbuild.yaml
Labels: cla: yes

#940 builds: drop support for MacOS
  .bazelrc
  WORKSPACE
  docs/INSTALL-OSX.md
  scripts/build_server
  scripts/run_tests
Labels: cla: yes

#934 Integrate cargo-deny checks into CI
  Dockerfile
  cloudbuild.yaml
  deny.toml
  examples/abitest/abitest_common/Cargo.toml
  examples/abitest/module_0/rust/Cargo.toml
  examples/abitest/module_1/rust/Cargo.toml
  examples/abitest/tests/Cargo.toml
  examples/aggregator/backend/Cargo.toml
  examples/aggregator/common/Cargo.toml
  examples/aggregator/module/rust/Cargo.toml
  examples/authentication/server/Cargo.toml
  examples/chat/module/rust/Cargo.toml
  examples/hello_world/module/rust/Cargo.toml
  examples/machine_learning/module/rust/Cargo.toml
  examples/private_set_intersection/module/rust/Cargo.toml
  examples/running_average/module/rust/Cargo.toml
  examples/rustfmt/module/rust/Cargo.toml
  examples/translator/common/Cargo.toml
  examples/translator/module/rust/Cargo.toml
  experimental/split_grpc/client/Cargo.toml
  experimental/split_grpc/proxy/Cargo.toml
  experimental/split_grpc/server/Cargo.toml
  runner/Cargo.toml
  scripts/check_cargo_deny
  third_party/expect/Cargo.toml
Labels: cla: yes

#838 Add TLS handling to the gRPC pseudo-node
  cargo/remote/ring-0.16.12.BUILD
  cloudbuild.yaml
  oak/proto/application.proto
  oak/server/rust/oak_loader/src/main.rs
  oak/server/rust/oak_runtime/Cargo.toml
  oak/server/rust/oak_runtime/src/config.rs
  oak/server/rust/oak_runtime/src/node/grpc_server.rs
  oak/server/rust/oak_runtime/src/node/mod.rs
  oak/server/rust/oak_runtime/src/proto/oak.application.rs
  scripts/run_server
  sdk/rust/oak/src/grpc/mod.rs
  sdk/rust/oak/src/grpc/server.rs
Labels: cla: yes

#946 Move gRPC server to a separate directory
  oak/server/rust/oak_runtime/src/node/grpc/mod.rs
  oak/server/rust/oak_runtime/src/node/grpc/server.rs
  oak/server/rust/oak_runtime/src/node/mod.rs
Labels: cla: yes

#947 Address cargo deny license-specific warnings
  deny.toml
Labels: cla: yes

#948 Remove invisible chart edges
  oak/server/rust/oak_runtime/src/runtime/introspect.rs
Labels: cla: yes

#925 auth_server: Exchange auth code for identity token
  Cargo.lock
  examples/authentication/README.md
  examples/authentication/client/src/auth_client.rs
  examples/authentication/client/src/main.rs
  examples/authentication/proto/authentication.proto
  examples/authentication/server/Cargo.toml
  examples/authentication/server/src/auth_handler.rs
  examples/authentication/server/src/main.rs
  examples/authentication/server/src/token_exchanger.rs
Labels: cla: yes

#949 Use `RUST_LOG` in `simple_logger`
  oak/server/rust/oak_loader/src/main.rs
Labels: cla: yes

#951 Track handles in `channel_read`
  oak/server/rust/oak_runtime/src/runtime/mod.rs
Labels: cla: yes

#950 Move codec to a separate directory
  oak/server/rust/oak_runtime/src/node/grpc/codec.rs
  oak/server/rust/oak_runtime/src/node/grpc/mod.rs
  oak/server/rust/oak_runtime/src/node/grpc/server.rs
Labels: cla: yes

#952 Fix gRPC request handling
  oak/server/rust/oak_runtime/src/node/grpc/server.rs
Labels: cla: yes

#937 Update the chat example README for clarity & currency
  examples/chat/README.md
Labels: cla: yes

#957 Delete an unused variable
  scripts/run_examples
Labels: cla: yes

#959 Introspection Server: Use 405 http status code for disallowed methods
  oak/server/rust/oak_runtime/src/runtime/introspect.rs
Labels: cla: yes, lang/Rust

#963 Fix GrpsResponse handling
  oak/server/rust/oak_runtime/src/node/grpc/server.rs
  sdk/rust/oak/src/grpc/mod.rs
  sdk/rust/oak/src/grpc/server.rs
Labels: cla: yes

#967 LICENSE: fill in copyright placeholder
  LICENSE
Labels: cla: yes

#964 runtime: improve comments
  oak/server/rust/oak_runtime/src/metrics/server.rs
  oak/server/rust/oak_runtime/src/node/external.rs
  oak/server/rust/oak_runtime/src/node/grpc/server.rs
  oak/server/rust/oak_runtime/src/node/logger.rs
  oak/server/rust/oak_runtime/src/node/mod.rs
  oak/server/rust/oak_runtime/src/node/wasm/mod.rs
  oak/server/rust/oak_runtime/src/runtime/channel.rs
  oak/server/rust/oak_runtime/src/runtime/introspect.rs
  oak/server/rust/oak_runtime/src/runtime/mod.rs
Labels: cla: yes

#960 Return immediately from wait if at least one invalid channel
  docs/abi.md
  oak/proto/oak_abi.proto
  oak/server/rust/oak_abi/src/proto/oak_abi.rs
  oak/server/rust/oak_runtime/src/node/wasm/mod.rs
  oak/server/rust/oak_runtime/src/runtime/mod.rs
  oak/server/rust/oak_runtime/src/runtime/tests.rs
  sdk/rust/oak/src/lib.rs
Labels: cla: yes

#975 Assign labels on channel creation
  docs/abi.md
  examples/abitest/module_0/rust/src/lib.rs
  examples/aggregator/README.md
  examples/aggregator/module/rust/Cargo.toml
  examples/aggregator/module/rust/src/lib.rs
  oak/server/rust/oak_abi/src/lib.rs
  oak/server/rust/oak_glue/src/lib.rs
  oak/server/rust/oak_runtime/src/node/grpc/server.rs
  oak/server/rust/oak_runtime/src/node/wasm/mod.rs
  oak/server/rust/oak_runtime/src/node/wasm/tests.rs
  oak/server/rust/oak_runtime/src/runtime/mod.rs
  oak/server/rust/oak_runtime/src/runtime/tests.rs
  sdk/rust/oak/src/grpc/client.rs
  sdk/rust/oak/src/io/mod.rs
  sdk/rust/oak/src/lib.rs
  sdk/rust/oak_tests/src/lib.rs
Labels: cla: yes

#979 Redirect ABI method comments to documentation
  docs/abi.md
  oak/server/rust/oak_runtime/src/node/wasm/mod.rs
Labels: cla: yes

#981 Improve channel docs
  docs/concepts.md
  docs/images/InvocationPattern.gif
  docs/images/InvocationPattern.png
Labels: cla: yes

#987 runtime: use hyper's with_graceful_shutdown()
  oak/server/rust/oak_runtime/src/metrics/server.rs
  oak/server/rust/oak_runtime/src/runtime/introspect.rs
Labels: cla: yes

#941 Manage prometheus registry in Oak Runtime
  oak/server/rust/oak_runtime/src/metrics/mod.rs
  oak/server/rust/oak_runtime/src/metrics/server.rs
  oak/server/rust/oak_runtime/src/node/grpc/server.rs
  oak/server/rust/oak_runtime/src/runtime/mod.rs
  oak/server/rust/oak_runtime/tests/integration_test.rs
Labels: cla: yes

#983 Add TLS support to Android Hello World Client
  WORKSPACE
  examples/aggregator/client/android/BUILD
  examples/aggregator/client/android/cpp/client.cc
  examples/aggregator/client/android/java/com/google/oak/aggregator/MainActivity.java
  examples/certs/AndroidManifest.xml
  examples/certs/BUILD
  examples/certs/local/ca.pem
  examples/certs/local/local.ext
  examples/certs/local/local.pem
  examples/hello_world/client/android/BUILD
  examples/hello_world/client/android/cpp/client.cc
  examples/hello_world/client/android/java/com/google/oak/hello_world/MainActivity.java
  examples/hello_world/proto/BUILD
  examples/hello_world/proto/hello_world.proto
Labels: cla: yes

#992 Update comments in Oak Loader
  oak/server/rust/oak_loader/src/main.rs
Labels: cla: yes

#985 Use futures select for stopping gRPC nodes
  cloudbuild.yaml
  examples/abitest/module_0/rust/src/lib.rs
  oak/server/rust/oak_runtime/src/config.rs
  oak/server/rust/oak_runtime/src/node/external.rs
  oak/server/rust/oak_runtime/src/node/grpc/client.rs
  oak/server/rust/oak_runtime/src/node/grpc/server.rs
  oak/server/rust/oak_runtime/src/node/logger.rs
  oak/server/rust/oak_runtime/src/node/mod.rs
  oak/server/rust/oak_runtime/src/node/wasm/mod.rs
  oak/server/rust/oak_runtime/src/runtime/mod.rs
  oak/server/rust/oak_runtime/src/runtime/tests.rs
Labels: cla: yes

#994 Add runtime health-check metric
  oak/server/rust/oak_runtime/src/metrics/mod.rs
  oak/server/rust/oak_runtime/src/runtime/mod.rs
  oak/server/rust/oak_runtime/tests/integration_test.rs
Labels: cla: yes

#984 Support downgrade of tags
  docs/concepts.md
  oak/server/rust/oak_runtime/src/runtime/mod.rs
  oak/server/rust/oak_runtime/src/runtime/tests.rs
Labels: cla: yes

#997 Make scripts fail if any part of a pipeline fails
  scripts/build_reproducibility_index
  scripts/common
Labels: cla: yes

#995 Move blocking Android code to a background thread
  examples/aggregator/client/android/cpp/client.cc
  examples/aggregator/client/android/java/com/google/oak/aggregator/MainActivity.java
  examples/aggregator/client/android/java/com/google/oak/aggregator/res/layout/activity_main.xml
  examples/hello_world/client/android/java/com/google/oak/hello_world/MainActivity.java
  examples/hello_world/client/android/java/com/google/oak/hello_world/res/layout/activity_main.xml
Labels: cla: yes

#996 Add prometheus-to-sd to scrape metrics
  examples/aggregator/README.md
  examples/aggregator/gcp/pod.yaml
Labels: cla: yes

#1000 Specify zone in gcloud command
  examples/aggregator/scripts/deploy
  examples/aggregator/scripts/undeploy
Labels: cla: yes

#1004 Introduce config map format and parsing logic
  Cargo.lock
  cargo/BUILD
  cargo/Cargo.lock
  cargo/Cargo.toml
  oak/proto/application.proto
  oak/server/rust/oak_loader/BUILD
  oak/server/rust/oak_loader/Cargo.toml
  oak/server/rust/oak_loader/src/main.rs
  oak/server/rust/oak_loader/src/tests.rs
  oak/server/rust/oak_runtime/src/proto/oak.application.rs
Labels: cla: yes

#998 runtime: cope with aux servers quitting first
  oak/server/rust/oak_runtime/src/runtime/mod.rs
Labels: cla: yes

#1005 Remove Fuzzing badge
  README.md
Labels: cla: yes

#1006 Add asserts to examples
  examples/private_set_intersection/client/private_set_intersection.cc
  examples/running_average/client/running_average.cc
Labels: cla: yes

#935 Add build examples and build server to runner
  runner/src/internal.rs
  runner/src/main.rs
  scripts/runner
Labels: cla: yes

#1008 Run `cargo clippy` before actual tests
  scripts/run_tests
Labels: cla: yes

#993 Use Rust Loader for running examples
  Cargo.lock
  cloudbuild.yaml
  docs/programming-oak.md
  examples/abitest/client/abitest.cc
  examples/abitest/config/config.textproto
  examples/abitest/module_0/rust/src/lib.rs
  examples/abitest/module_1/rust/src/lib.rs
  examples/aggregator/README.md
  examples/aggregator/backend/Cargo.toml
  examples/aggregator/backend/src/main.rs
  examples/aggregator/client/aggregator.cc
  examples/aggregator/config/config.textproto
  examples/aggregator/module/rust/src/lib.rs
  examples/aggregator/scripts/run_backend
  examples/aggregator/scripts/run_server
  examples/chat/client/chat.cc
  examples/chat/config/config.textproto
  examples/chat/module/rust/src/backend.rs
  examples/chat/module/rust/src/lib.rs
  examples/hello_world/client/hello_world.cc
  examples/hello_world/config/BUILD
  examples/hello_world/config/config.textproto
  examples/hello_world/config/config_translator.textproto
  examples/hello_world/module/rust/src/lib.rs
  examples/machine_learning/client/machine_learning.cc
  examples/machine_learning/config/config.textproto
  examples/machine_learning/module/rust/src/lib.rs
  examples/private_set_intersection/client/private_set_intersection.cc
  examples/private_set_intersection/config/config.textproto
  examples/private_set_intersection/module/rust/src/lib.rs
  examples/running_average/client/running_average.cc
  examples/running_average/config/config.textproto
  examples/running_average/module/rust/src/lib.rs
  examples/rustfmt/client/rustfmt.cc
  examples/rustfmt/config/config.textproto
  examples/rustfmt/module/rust/src/lib.rs
  examples/tensorflow/config/config.textproto
  examples/translator/client/translator.go
  examples/translator/config/config.textproto
  examples/translator/module/rust/src/lib.rs
  oak/server/rust/oak_runtime/src/config.rs
  oak/server/rust/oak_runtime/src/node/grpc/client.rs
  oak/server/rust/oak_runtime/src/node/grpc/mod.rs
  oak/server/rust/oak_runtime/src/node/grpc/server.rs
  oak/server/rust/oak_runtime/src/node/mod.rs
  oak/server/rust/oak_runtime/src/node/roughtime.rs
  oak/server/rust/oak_runtime/src/node/storage.rs
  scripts/build_example
  scripts/build_server
  scripts/run_example
  scripts/run_examples
  scripts/run_server
  sdk/rust/oak/src/grpc/client.rs
  sdk/rust/oak/src/grpc/server.rs
  sdk/rust/oak/src/lib.rs
Labels: cla: yes

#1010 Rename secrecy to confidentiality
  docs/concepts.md
  docs/development.md
  examples/aggregator/module/rust/src/lib.rs
  examples/chat/proto/chat.proto
  oak/common/label.cc
  oak/proto/label.proto
  oak/server/rust/oak_abi/src/label/mod.rs
  oak/server/rust/oak_abi/src/label/tests.rs
  oak/server/rust/oak_abi/src/proto/oak.label.rs
  oak/server/rust/oak_runtime/src/runtime/mod.rs
  oak/server/rust/oak_runtime/src/runtime/tests.rs
Labels: cla: yes

#1011 Do not override RUST_LOG
  scripts/common
Labels: cla: yes

#1012 Use Rust Oak Loader in Docker images
  BUILD
  examples/aggregator/README.md
  examples/aggregator/gcp/pod.yaml
  examples/tensorflow/config/BUILD
  oak/server/loader/BUILD
  oak/server/loader/oak_docker.bzl
  scripts/build_example
Labels: cla: yes

#1014 Move TLS parameters out of application config
  Cargo.lock
  docs/programming-oak.md
  examples/abitest/config/config.textproto
  examples/abitest/tests/src/tests.rs
  examples/aggregator/config/config.textproto
  examples/chat/config/config.textproto
  examples/hello_world/config/config.textproto
  examples/machine_learning/config/config.textproto
  examples/private_set_intersection/config/config.textproto
  examples/running_average/config/config.textproto
  examples/rustfmt/config/config.textproto
  examples/tensorflow/config/config.textproto
  examples/translator/config/config.textproto
  oak/proto/application.proto
  oak/server/rust/oak_glue/src/lib.rs
  oak/server/rust/oak_loader/BUILD
  oak/server/rust/oak_loader/Cargo.toml
  oak/server/rust/oak_loader/src/main.rs
  oak/server/rust/oak_runtime/src/config.rs
  oak/server/rust/oak_runtime/src/lib.rs
  oak/server/rust/oak_runtime/src/node/mod.rs
  oak/server/rust/oak_runtime/src/node/wasm/tests.rs
  oak/server/rust/oak_runtime/src/proto/oak.application.rs
  oak/server/rust/oak_runtime/src/runtime/mod.rs
  oak/server/rust/oak_runtime/src/runtime/tests.rs
  oak/server/rust/oak_runtime/tests/integration_test.rs
  sdk/rust/oak_tests/src/lib.rs
Labels: cla: yes

#1015 Re-include oak_loader in reproducibility index
  scripts/build_reproducibility_index
Labels: cla: yes

#1001 Collect metrics using stackdriver-prometheus-sidecar
  examples/aggregator/README.md
  examples/aggregator/gcp/deployment.yaml
  examples/aggregator/gcp/metrics-sidecar.yaml
  examples/aggregator/gcp/pod.yaml
  examples/aggregator/scripts/deploy
  examples/aggregator/scripts/undeploy
  oak/server/rust/oak_glue/src/lib.rs
  oak/server/rust/oak_loader/src/main.rs
Labels: cla: yes

#1017 Add simple Node.js client
  .gitignore
  examples/hello_world/client/nodejs/README.MD
  examples/hello_world/client/nodejs/index.js
  examples/hello_world/client/nodejs/package-lock.json
  examples/hello_world/client/nodejs/package.json
Labels: cla: yes

#1018 runtime: use 'confidential' rather than 'secret'
  oak/server/rust/oak_runtime/src/runtime/mod.rs
  oak/server/rust/oak_runtime/src/runtime/tests.rs
Labels: cla: yes

#1026 examples: use localhost address in tensorflow client
  examples/tensorflow/client/tensorflow.cc
Labels: cla: yes

#1025 Move the creation of Runtime dot graph to a separate submodule
  oak/server/rust/oak_runtime/src/runtime/channel.rs
  oak/server/rust/oak_runtime/src/runtime/graph.rs
  oak/server/rust/oak_runtime/src/runtime/introspect.rs
  oak/server/rust/oak_runtime/src/runtime/mod.rs
Labels: cla: yes

#1031 Print reproducibility index diff
  .github/workflows/reproducibility.yaml
Labels: cla: yes

#1030 Fix format of `random_get` header
  docs/abi.md
Labels: cla: yes

#1028 Use localhost instead of 127.0.0.1 in docs
  docs/development.md
  examples/aggregator/README.md
  examples/chat/README.md
Labels: cla: yes

#1034 Make oak_abi a standalone crate
  Cargo.toml
  examples/aggregator/module/rust/Cargo.toml
  oak_abi/Cargo.toml
  oak_abi/build.rs
  oak_abi/src/grpc/mod.rs
  oak_abi/src/label/mod.rs
  oak_abi/src/label/tests.rs
  oak_abi/src/lib.rs
  oak_abi/src/proto/mod.rs
Labels: cla: yes

#1033 Fix name of `public_untrusted` label
  examples/abitest/module_0/rust/src/lib.rs
  examples/aggregator/module/rust/src/lib.rs
  oak/server/rust/oak_glue/src/lib.rs
  oak/server/rust/oak_runtime/src/node/grpc/server/mod.rs
  oak/server/rust/oak_runtime/src/node/wasm/tests.rs
  oak/server/rust/oak_runtime/src/runtime/mod.rs
  oak_abi/src/label/mod.rs
  oak_abi/src/label/tests.rs
  sdk/rust/oak/src/grpc/client.rs
  sdk/rust/oak/src/lib.rs
  sdk/rust/oak_tests/src/lib.rs
Labels: cla: yes

#1035 Add initial pristine commit of roughenough 1.1.8
  third_party/roughenough/.drone.yml
  third_party/roughenough/.gitignore
  third_party/roughenough/.travis.yml
  third_party/roughenough/CHANGELOG.md
  third_party/roughenough/CONTRIBUTING.md
  third_party/roughenough/Cargo.toml
  third_party/roughenough/Dockerfile
  third_party/roughenough/LICENSE
  third_party/roughenough/README.md
  third_party/roughenough/benches/roughenough-bench.rs
  third_party/roughenough/doc/OPTIONAL-FEATURES.md
  third_party/roughenough/example.cfg
  third_party/roughenough/src/bin/roughenough-client.rs
  third_party/roughenough/src/bin/roughenough-kms.rs
  third_party/roughenough/src/bin/roughenough-server.rs
  third_party/roughenough/src/config/environment.rs
  third_party/roughenough/src/config/file.rs
  third_party/roughenough/src/config/memory.rs
  third_party/roughenough/src/config/mod.rs
  third_party/roughenough/src/error.rs
  third_party/roughenough/src/grease.rs
  third_party/roughenough/src/key/longterm.rs
  third_party/roughenough/src/key/mod.rs
  third_party/roughenough/src/key/online.rs
  third_party/roughenough/src/kms/awskms.rs
  third_party/roughenough/src/kms/envelope.rs
  third_party/roughenough/src/kms/gcpkms.rs
  third_party/roughenough/src/kms/mod.rs
  third_party/roughenough/src/lib.rs
  third_party/roughenough/src/merkle.rs
  third_party/roughenough/src/message.rs
  third_party/roughenough/src/server.rs
  third_party/roughenough/src/sign.rs
  third_party/roughenough/src/stats/aggregated.rs
  third_party/roughenough/src/stats/mod.rs
  third_party/roughenough/src/stats/per_client.rs
  third_party/roughenough/src/tag.rs
Labels: cla: yes

#1039 Exclude `oak_abi` and `oak_utils` from the workspace
  Cargo.toml
  oak_abi/Cargo.lock
  oak_abi/Cargo.toml
  oak_utils/Cargo.lock
  oak_utils/Cargo.toml
  oak_utils/src/lib.rs
Labels: cla: yes

#1044 Use separate target dir when compiling Wasm code
  BUILD
  Cargo.lock
  examples/abitest/config/BUILD
  examples/aggregator/config/BUILD
  examples/chat/config/BUILD
  examples/hello_world/config/BUILD
  examples/machine_learning/config/BUILD
  examples/private_set_intersection/config/BUILD
  examples/running_average/config/BUILD
  examples/rustfmt/config/BUILD
  examples/translator/config/BUILD
  scripts/build_example
  scripts/build_reproducibility_index
  scripts/check_formatting
  scripts/format
  sdk/rust/oak_tests/Cargo.toml
  sdk/rust/oak_tests/src/lib.rs
Labels: cla: yes

#1043 Change roughenough to a client library only
  Cargo.lock
  Cargo.toml
  third_party/roughenough/.drone.yml
  third_party/roughenough/.gitignore
  third_party/roughenough/.travis.yml
  third_party/roughenough/CHANGELOG.md
  third_party/roughenough/CONTRIBUTING.md
  third_party/roughenough/Cargo.toml
  third_party/roughenough/Dockerfile
  third_party/roughenough/README.md
  third_party/roughenough/benches/roughenough-bench.rs
  third_party/roughenough/doc/OPTIONAL-FEATURES.md
  third_party/roughenough/example.cfg
  third_party/roughenough/src/bin/roughenough-client.rs
  third_party/roughenough/src/bin/roughenough-kms.rs
  third_party/roughenough/src/bin/roughenough-server.rs
  third_party/roughenough/src/client.rs
  third_party/roughenough/src/config/environment.rs
  third_party/roughenough/src/config/file.rs
  third_party/roughenough/src/config/memory.rs
  third_party/roughenough/src/config/mod.rs
  third_party/roughenough/src/error.rs
  third_party/roughenough/src/grease.rs
  third_party/roughenough/src/key/longterm.rs
  third_party/roughenough/src/key/mod.rs
  third_party/roughenough/src/key/online.rs
  third_party/roughenough/src/kms/awskms.rs
  third_party/roughenough/src/kms/envelope.rs
  third_party/roughenough/src/kms/gcpkms.rs
  third_party/roughenough/src/kms/mod.rs
  third_party/roughenough/src/lib.rs
  third_party/roughenough/src/merkle.rs
  third_party/roughenough/src/message.rs
  third_party/roughenough/src/server.rs
  third_party/roughenough/src/sign.rs
  third_party/roughenough/src/stats/aggregated.rs
  third_party/roughenough/src/stats/mod.rs
  third_party/roughenough/src/stats/per_client.rs
Labels: cla: yes

#1048 Docs: Remove orphaned bullet point from the table of contents
  docs/concepts.md
Labels: cla: yes, documentation

#1046 Take into account downgrade privilege when reading
  oak/server/rust/oak_runtime/src/runtime/mod.rs
  oak/server/rust/oak_runtime/src/runtime/tests.rs
Labels: cla: yes
