Repository project-oak/oak, pull requests merged in 2021-06, with the labels that each got.

#2154 Check in `fuzzable.wasm` to git
  .github/workflows/ci.yaml
  oak_functions/loader/fuzz/Cargo.lock
  oak_functions/loader/fuzz/Cargo.toml
  oak_functions/loader/fuzz/fuzz.toml
  oak_functions/loader/fuzz/fuzz_targets/data/fuzzable.wasm
  oak_functions/loader/fuzz/fuzz_targets/wasm_invoke.rs
  runner/src/examples.rs
  runner/src/files.rs
  runner/src/internal.rs
  runner/src/main.rs
Labels: cla: yes

#2159 Fix a template type and format java files
  oak_functions/client/java/src/com/google/oak/functions/client/AttestationClient.java
Labels: cla: yes

#2160 Format AttestationCleint.java
  oak_functions/client/java/src/com/google/oak/functions/client/AttestationClient.java
Labels: cla: yes

#2161 Refactor Java attestation client
  oak_functions/client/java/BUILD
  oak_functions/client/java/src/com/google/oak/functions/client/AttestationClient.java
  oak_functions/examples/weather_lookup/client/java/BUILD
  oak_functions/examples/weather_lookup/example.toml
  remote_attestation/java/BUILD
  remote_attestation/java/src/com/google/oak/remote_attestation/AttestationStateMachine.java
  remote_attestation/java/src/com/google/oak/remote_attestation/crypto/AeadEncryptor.java
  remote_attestation/java/src/com/google/oak/remote_attestation/crypto/KeyNegotiator.java
  remote_attestation/java/src/com/google/oak/remote_attestation/crypto/tink/AeadEncryptor.java
  remote_attestation/java/src/com/google/oak/remote_attestation/crypto/tink/KeyNegotiator.java
Labels: cla: yes

#2169 Optimize fuzz input of wasm_invoke to avoid timeouts
  oak_functions/loader/fuzz/fuzz_targets/wasm_invoke.rs
  oak_utils/src/lib.rs
Labels: cla: yes

#2145 Add Android client for Oak Functions
  oak_functions/client/android/AndroidManifest.xml
  oak_functions/client/android/BUILD
  oak_functions/client/android/com/google/oak/functions/android/client/MainActivity.java
  oak_functions/client/android/com/google/oak/functions/android/client/res/layout/activity_main.xml
  oak_functions/client/android/com/google/oak/functions/android/client/res/values/colors.xml
  oak_functions/client/android/com/google/oak/functions/android/client/res/values/strings.xml
  oak_functions/examples/weather_lookup/config.toml
Labels: cla: yes

#2175 Add cache to ignored paths in runner
  runner/src/files.rs
Labels: cla: yes

#2173 Add experimental streaming gRPC client and server
  experimental/Cargo.lock
  experimental/Cargo.toml
  experimental/gcp_api_gateway/.dockerignore
  experimental/gcp_api_gateway/Dockerfile
  experimental/gcp_api_gateway/client/Cargo.toml
  experimental/gcp_api_gateway/client/build.rs
  experimental/gcp_api_gateway/client/src/main.rs
  experimental/gcp_api_gateway/config/api_config.yaml
  experimental/gcp_api_gateway/scripts/deploy_api
  experimental/gcp_api_gateway/scripts/deploy_server
  experimental/gcp_api_gateway/server/Cargo.toml
  experimental/gcp_api_gateway/server/build.rs
  experimental/gcp_api_gateway/server/src/main.rs
Labels: cla: yes

#2182 Use random nonce in Remote Attestation
  remote_attestation/rust/src/crypto.rs
Labels: cla: yes

#2183 Use HKDF to derive session key in Remote Attestation
  oak_functions/client/android/BUILD
  oak_functions/client/java/BUILD
  oak_functions/examples/weather_lookup/client/java/BUILD
  oak_functions/examples/weather_lookup/example.toml
  remote_attestation/java/BUILD
  remote_attestation/java/src/com/google/oak/remote_attestation/AeadEncryptor.java
  remote_attestation/java/src/com/google/oak/remote_attestation/AttestationStateMachine.java
  remote_attestation/java/src/com/google/oak/remote_attestation/KeyNegotiator.java
  remote_attestation/java/src/com/google/oak/remote_attestation/crypto/AeadEncryptor.java
  remote_attestation/java/src/com/google/oak/remote_attestation/crypto/KeyNegotiator.java
  remote_attestation/java/src/com/google/oak/remote_attestation/crypto/tink/KeyNegotiator.java
  remote_attestation/rust/src/crypto.rs
Labels: cla: yes

#2174 Use repo's root as the `proto_path` in calls to `compile_proto`
  docs/programming-oak.md
  examples/abitest/grpc/build.rs
  examples/abitest/module_0/rust/build.rs
  examples/aggregator/backend/build.rs
  examples/aggregator/grpc/build.rs
  examples/aggregator/module/rust/build.rs
  examples/aggregator/proto/aggregator_init.proto
  examples/authentication/client/build.rs
  examples/chat/grpc/build.rs
  examples/chat/module/rust/build.rs
  examples/hello_world/grpc/build.rs
  examples/hello_world/module/rust/build.rs
  examples/http_server/module/build.rs
  examples/injection/module/rust/build.rs
  examples/private_set_intersection/client/rust/build.rs
  examples/private_set_intersection/grpc/build.rs
  examples/private_set_intersection/handler_module/rust/build.rs
  examples/proxy_attestation/client/rust/build.rs
  examples/proxy_attestation/module/rust/build.rs
  examples/translator/common/build.rs
  examples/translator/grpc/build.rs
  examples/trusted_database/client/rust/build.rs
  examples/trusted_database/module/rust/build.rs
  examples/trusted_database/proto/trusted_database_init.proto
  experimental/benchmark/build.rs
  experimental/gcp_api_gateway/client/build.rs
  experimental/gcp_api_gateway/server/build.rs
  experimental/proxy_attestation/build.rs
  experimental/split_grpc/client/build.rs
  experimental/split_grpc/server/build.rs
  oak_abi/build.rs
  oak_functions/abi/build.rs
  oak_functions/examples/fuzzable/module/build.rs
  oak_functions/loader/fuzz/build.rs
  oak_io/build.rs
  oak_runtime/build.rs
  oak_services/build.rs
  oak_utils/src/lib.rs
  remote_attestation/rust/build.rs
  sdk/rust/oak/build.rs
  sdk/rust/oak/tests/handle_extract_inject.proto
Labels: cla: yes

#2185 Use separate session keys in Remote Attestation
  oak_functions/client/java/src/com/google/oak/functions/client/AttestationClient.java
  oak_functions/client/rust/src/attestation.rs
  oak_functions/loader/src/attestation.rs
  remote_attestation/java/BUILD
  remote_attestation/java/src/com/google/oak/remote_attestation/AeadEncryptor.java
  remote_attestation/java/src/com/google/oak/remote_attestation/AttestationEngine.java
  remote_attestation/java/src/com/google/oak/remote_attestation/AttestationStateMachine.java
  remote_attestation/java/src/com/google/oak/remote_attestation/KeyNegotiator.java
  remote_attestation/rust/src/attestation.rs
  remote_attestation/rust/src/crypto.rs
Labels: cla: yes

#2189 Add separate Android targets to Oak Functions
  oak_functions/client/android/BUILD
  oak_functions/client/java/BUILD
  remote_attestation/java/BUILD
  scripts/build_example_android
  scripts/build_examples_android
Labels: cla: yes

#2165 Update deploy scripts
  oak_functions/client/rust/Cargo.lock
  oak_functions/client/rust/Cargo.toml
  oak_functions/client/rust/README.md
  oak_functions/examples/Cargo.lock
  oak_functions/examples/key_value_lookup/config.toml
  oak_functions/examples/weather_lookup/README.md
  oak_functions/examples/weather_lookup/client/java/src/Main.java
  oak_functions/examples/weather_lookup/config.toml
  oak_functions/examples/weather_lookup/scripts/cloud_run_deploy
  oak_functions/gcp/README.md
  oak_functions/gcp/endpoint_api_config.yaml.template
  oak_functions/load_test/Cargo.lock
  oak_functions/loader/Cargo.lock
  oak_functions/loader/src/main.rs
  oak_functions/sdk/Cargo.lock
  runner/src/examples.rs
  runner/src/files.rs
  runner/src/internal.rs
  runner/src/main.rs
  scripts/deploy_oak_functions_api
  scripts/deploy_oak_functions_endpoints
  scripts/deploy_oak_functions_loader
  scripts/gcloud_build_image
  scripts/gcp_common
Labels: cla: yes

#2190 Add TLS/gRPC connections to Java Oak Functions
  oak_functions/client/android/com/google/oak/functions/android/client/MainActivity.java
  oak_functions/client/java/src/com/google/oak/functions/client/AttestationClient.java
  oak_functions/examples/weather_lookup/client/java/src/Main.java
Labels: cla: yes

#2191 Use non-empty lookup data for wasm_invoke fuzz target
  oak_functions/loader/fuzz/Cargo.lock
  oak_functions/loader/fuzz/Cargo.toml
  oak_functions/loader/fuzz/fuzz_targets/wasm_invoke.rs
  oak_functions/loader/src/lookup.rs
Labels: cla: yes

#2194 Remove GCP certs from Oak Functions Android client
  oak_functions/client/android/BUILD
Labels: cla: yes

#2052 Weather lookup example with sparse data
  oak_functions/examples/weather_lookup/README.md
  oak_functions/examples/weather_lookup/client/java/src/Main.java
  oak_functions/examples/weather_lookup/config.toml
  oak_functions/examples/weather_lookup/example.toml
  oak_functions/examples/weather_lookup/module/src/lib.rs
  oak_functions/examples/weather_lookup/module/src/tests.rs
  oak_functions/loader/src/main.rs
  oak_functions/loader/src/server.rs
  oak_functions/loader/src/tests.rs
  oak_functions/lookup_data_generator/README.md
  oak_functions/lookup_data_generator/src/main.rs
  scripts/generate_and_upload_lookup_data_weather
Labels: cla: yes

#2168 Run runner cargo commands only for modified crates
  runner/Cargo.lock
  runner/Cargo.toml
  runner/src/diffs.rs
  runner/src/examples.rs
  runner/src/files.rs
  runner/src/internal.rs
  runner/src/main.rs
  scripts/check_docs
Labels: WIP, cla: yes

#2203 Align Oak Functions Android Client with Java and Android best practices
  oak_functions/client/android/AndroidManifest.xml
  oak_functions/client/android/BUILD
  oak_functions/client/android/com/google/oak/functions/android/client/MainActivity.java
  oak_functions/client/android/com/google/oak/functions/android/client/res/values/strings.xml
  oak_functions/client/java/BUILD
  oak_functions/client/java/src/com/google/oak/functions/client/AttestationClient.java
  oak_functions/examples/weather_lookup/client/java/src/Main.java
  oak_functions/proto/BUILD
  remote_attestation/java/BUILD
  remote_attestation/java/src/com/google/oak/remote_attestation/AeadEncryptor.java
  remote_attestation/java/src/com/google/oak/remote_attestation/AttestationEngine.java
  remote_attestation/java/src/com/google/oak/remote_attestation/KeyNegotiator.java
  remote_attestation/proto/BUILD
Labels: Oak Functions, cla: yes

#2206 Ignore result from Oak Functions SDK log macro
  oak_functions/examples/weather_lookup/module/src/lib.rs
  oak_functions/sdk/oak_functions/src/lib.rs
Labels: Oak Functions, cla: yes

#2207 Adddress additional best-practice suggestions for Oak Functions Android Client
  oak_functions/client/android/com/google/oak/functions/android/client/MainActivity.java
  oak_functions/client/android/com/google/oak/functions/android/client/res/values/strings.xml
  oak_functions/client/java/BUILD
  oak_functions/client/java/src/com/google/oak/functions/client/AttestationClient.java
  oak_functions/examples/weather_lookup/client/java/src/Main.java
  oak_functions/examples/weather_lookup/example.toml
Labels: Oak Functions, cla: yes

#2210 Use clang formatting for .java files
  runner/src/files.rs
Labels: cla: yes

#2208 Make Oak Functions cloud run service private
  oak_functions/client/rust/src/main.rs
  oak_functions/examples/weather_lookup/client/java/src/Main.java
  oak_functions/examples/weather_lookup/example.toml
  oak_functions/examples/weather_lookup/scripts/cloud_run_deploy
  scripts/deploy_oak_functions_endpoints
  scripts/deploy_oak_functions_loader
Labels: cla: yes

#2217 Fix the timeout problem in wasm_invoke fuzz target
  .github/workflows/ci.yaml
  oak_functions/examples/fuzzable/module/src/lib.rs
  oak_functions/loader/fuzz/fuzz_targets/data/fuzzable.wasm
  oak_functions/loader/fuzz/fuzz_targets/wasm_invoke.rs
  runner/src/internal.rs
  runner/src/main.rs
Labels: cla: yes
