Repository project-oak/oak, pull requests merged in 2021-05, with the labels that each got.

#2054 Give write permissions on pull requests rather than issues for Reproducibility Index workflow
  .github/workflows/reproducibility.yaml
  examples/deny.toml
  experimental/deny.toml
  oak_loader/deny.toml
  oak_runtime/deny.toml
  sdk/deny.toml
Labels: cla: yes

#2043 Use a custom response in Oak Functions
  oak_functions/abi/build.rs
  oak_functions/abi/src/lib.rs
  oak_functions/examples/Cargo.lock
  oak_functions/examples/weather_lookup/module/Cargo.toml
  oak_functions/examples/weather_lookup/module/src/tests.rs
  oak_functions/loader/src/server.rs
  oak_functions/loader/src/tests.rs
  oak_functions/proto/response.proto
Labels: cla: yes

#1980 Enable HTTPS fetching of lookup data
  oak_functions/examples/Cargo.lock
  oak_functions/examples/deny.toml
  oak_functions/examples/weather_lookup/config.toml
  oak_functions/loader/Cargo.lock
  oak_functions/loader/Cargo.toml
  oak_functions/loader/deny.toml
  oak_functions/loader/src/lookup.rs
Labels: cla: yes

#2057 Include policy-padding in the response body
  oak_functions/abi/src/lib.rs
  oak_functions/examples/weather_lookup/module/src/tests.rs
  oak_functions/loader/src/main.rs
  oak_functions/loader/src/server.rs
  oak_functions/loader/src/tests.rs
  oak_functions/proto/response.proto
Labels: cla: yes

#2058 Add support for logging to the functions SDK
  oak_functions/examples/weather_lookup/module/src/lib.rs
  oak_functions/loader/src/logger.rs
  oak_functions/loader/src/server.rs
  oak_functions/sdk/oak_functions/src/lib.rs
Labels: Oak Functions, cla: yes

#1946 Add HTTPS Attestation Service
  examples/Cargo.lock
  examples/Cargo.toml
  examples/https_attestation/backend/Cargo.toml
  examples/https_attestation/backend/src/main.rs
  examples/https_attestation/client/Cargo.toml
  examples/https_attestation/client/src/main.rs
  examples/https_attestation/example.toml
  experimental/Cargo.lock
  experimental/Cargo.toml
  experimental/attestation_common/Cargo.toml
  experimental/attestation_common/src/keying_material.rs
  experimental/attestation_common/src/lib.rs
  experimental/attestation_common/src/report.rs
  experimental/https_attestation/Cargo.toml
  experimental/https_attestation/src/main.rs
  experimental/https_attestation/src/server.rs
  oak_client/Cargo.lock
  oak_loader/Cargo.lock
Labels: cla: yes

#2065 Add new runner command for running fuzz targets
  .github/workflows/ci.yaml
  docs/development.md
  runner/src/internal.rs
  runner/src/main.rs
Labels: cla: yes

#2084 Fix condition for running functions examples
  runner/src/examples.rs
Labels: cla: yes

#2088 Bump libfuzzer-sys version
  oak_functions/loader/fuzz/Cargo.lock
Labels: cla: yes

#2097 Update Oak Functions deps
  oak_functions/loader/Cargo.lock
Labels: cla: yes

#2098 Fix curl command line in client script
  oak_functions/examples/weather_lookup/client/client
Labels: cla: yes

#2099 Update git_check_diff to check the presence of any newly generated files
  scripts/git_check_diff
Labels: cla: yes

#2104 Deploy GCP API Gateway for the Oak Functions weather lookup example
  oak_functions/client/Cargo.lock
  oak_functions/client/Cargo.toml
  oak_functions/gcp/README.md
  oak_functions/gcp/api_config.yaml.template
  scripts/deploy_oak_functions_api
  scripts/deploy_oak_functions_loader
  scripts/gcp_common
Labels: Oak Functions, cla: yes

#2111 Add flag to Oak Functions client to pass request
  oak_functions/client/README.md
  oak_functions/client/src/main.rs
  oak_functions/examples/Cargo.lock
  oak_functions/examples/Cargo.toml
  oak_functions/examples/key_value_lookup/example.toml
  oak_functions/examples/weather_lookup/client/client
  oak_functions/examples/weather_lookup/client/rust/Cargo.toml
  oak_functions/examples/weather_lookup/client/rust/build.rs
  oak_functions/examples/weather_lookup/client/rust/src/main.rs
  oak_functions/examples/weather_lookup/example.toml
  scripts/deploy_oak_functions_loader
Labels: cla: yes

#2118 Update various Rust deps
  examples/Cargo.lock
  examples/aggregator/README.md
  examples/aggregator/client/android/cpp/client.cc
  examples/aggregator/client/cpp/aggregator.cc
  examples/aggregator/config.toml
  examples/private_set_intersection/private_set_intersection_handler.sign
  oak_loader/Cargo.lock
  oak_runtime/Cargo.lock
  runner/Cargo.lock
Labels: cla: yes

#2110 Run test_long_response_time with multiple threads
  oak_functions/loader/src/server.rs
  oak_functions/loader/src/tests.rs
Labels: cla: yes

#2114 Add fuzzer for WasmHandler
  docs/development.md
  oak_functions/examples/Cargo.lock
  oak_functions/examples/Cargo.toml
  oak_functions/examples/fuzzable/README.md
  oak_functions/examples/fuzzable/module/Cargo.toml
  oak_functions/examples/fuzzable/module/build.rs
  oak_functions/examples/fuzzable/module/src/lib.rs
  oak_functions/examples/fuzzable/module/src/tests.rs
  oak_functions/loader/fuzz/Cargo.lock
  oak_functions/loader/fuzz/Cargo.toml
  oak_functions/loader/fuzz/build.rs
  oak_functions/loader/fuzz/fuzz_targets/wasm_invoke.rs
  oak_functions/loader/fuzz/proto/instructions.proto
Labels: Oak Functions, cla: yes

#2112 Add Java client for gRPC Attestation
  .github/workflows/ci.yaml
  WORKSPACE
  android.Dockerfile
  experimental/attestation_common/src/crypto.rs
  experimental/grpc_attestation/proto/BUILD
  experimental/grpc_attestation/proto/grpc_attestation.proto
  experimental/grpc_attestation/src/attestation.rs
  experimental/grpc_attestation/src/main.rs
  experimental/grpc_attestation_client/java/BUILD
  experimental/grpc_attestation_client/java/com/google/oak/grpc_attestation_client/AeadEncryptor.java
  experimental/grpc_attestation_client/java/com/google/oak/grpc_attestation_client/AttestationClient.java
  experimental/grpc_attestation_client/java/com/google/oak/grpc_attestation_client/KeyNegotiator.java
  experimental/grpc_attestation_client/java/com/google/oak/grpc_attestation_client/Main.java
  experimental/grpc_attestation_client/rust/src/lib.rs
  third_party/google/tink/BUILD
  third_party/google/tink/Remove-android-from-java.patch
Labels: cla: yes

#2127 Update tink-rust crates to latest version
  examples/Cargo.lock
  examples/aggregator/client/android/cpp/client.cc
  examples/aggregator/client/cpp/aggregator.cc
  examples/aggregator/config.toml
  examples/deny.toml
  examples/grpc_attestation/client/Cargo.toml
  examples/private_set_intersection/private_set_intersection_handler.sign
  experimental/Cargo.lock
  experimental/deny.toml
  oak_loader/Cargo.lock
  oak_loader/deny.toml
  oak_runtime/Cargo.lock
  oak_runtime/deny.toml
  sdk/Cargo.lock
  sdk/deny.toml
Labels: cla: yes, dependencies

#2129 Add Java gRPC Attestation to the CI
  Dockerfile
  examples/grpc_attestation/example.toml
  experimental/grpc_attestation_client/java/README.md
Labels: cla: yes

#2130 Fix fuzz targets
  oak_functions/loader/fuzz/fuzz_targets/apply_policy.rs
  oak_functions/loader/fuzz/fuzz_targets/wasm_invoke.rs
Labels: cla: yes

#2132 Move Java gRPC Attestation client to Oak Functions
  examples/Cargo.toml
  examples/grpc_attestation/client/java/BUILD
  examples/grpc_attestation/client/java/README.md
  examples/grpc_attestation/client/java/src/Main.java
  examples/grpc_attestation/client/rust/Cargo.toml
  examples/grpc_attestation/client/rust/src/main.rs
  examples/grpc_attestation/example.toml
  oak_functions/client/java/BUILD
  oak_functions/client/java/src/AeadEncryptor.java
  oak_functions/client/java/src/AttestationClient.java
  oak_functions/client/java/src/KeyNegotiator.java
Labels: cla: yes

#2133 Move gRPC Attestation proto to remote_attestation
  experimental/grpc_attestation/build.rs
  experimental/grpc_attestation/src/attestation.rs
  experimental/grpc_attestation/src/lib.rs
  experimental/grpc_attestation/src/main.rs
  experimental/grpc_attestation_client/rust/src/lib.rs
  oak_functions/client/java/BUILD
  oak_functions/client/java/src/AttestationClient.java
  remote_attestation/proto/BUILD
  remote_attestation/proto/remote_attestation.proto
Labels: cla: yes

#2137 Update .gitignore file
  .gitignore
Labels: cla: yes

#2138 Fix Java logging in gRPC Attestation
  examples/grpc_attestation/client/java/src/Main.java
  oak_functions/client/java/src/AttestationClient.java
Labels: cla: yes

#2139 Change deploy script for Oak Functions to run outside docker
  experimental/oak_functions_with_envoy/scripts/build.sh
  oak_functions/examples/weather_lookup/README.md
  scripts/deploy_oak_functions_loader
Labels: cla: yes

#2122 Add gRPC attestation support to Oak Functions
  experimental/grpc_attestation/src/attestation.rs
  experimental/grpc_attestation/src/lib.rs
  experimental/grpc_attestation/src/main.rs
  oak_functions/client/Cargo.lock
  oak_functions/client/Cargo.toml
  oak_functions/client/build.rs
  oak_functions/client/src/lib.rs
  oak_functions/client/src/main.rs
  oak_functions/examples/Cargo.lock
  oak_functions/examples/fuzzable/module/src/tests.rs
  oak_functions/examples/key_value_lookup/config.toml
  oak_functions/examples/key_value_lookup/module/src/tests.rs
  oak_functions/examples/weather_lookup/config.toml
  oak_functions/examples/weather_lookup/example.toml
  oak_functions/examples/weather_lookup/module/src/tests.rs
  oak_functions/gcp/api_config.yaml.template
  oak_functions/load_test/Cargo.lock
  oak_functions/load_test/src/main.rs
  oak_functions/loader/Cargo.lock
  oak_functions/loader/Cargo.toml
  oak_functions/loader/build.rs
  oak_functions/loader/fuzz/Cargo.lock
  oak_functions/loader/fuzz/fuzz_targets/wasm_invoke.rs
  oak_functions/loader/src/grpc.rs
  oak_functions/loader/src/lib.rs
  oak_functions/loader/src/main.rs
  oak_functions/loader/src/server.rs
  oak_functions/loader/src/tests.rs
  oak_functions/proto/server.proto
  oak_functions/sdk/Cargo.lock
  oak_functions/sdk/test_utils/src/lib.rs
  scripts/deploy_oak_functions_api
Labels: cla: yes

#2140 Use javax.crypto in Java gRPC Attestation
  experimental/attestation_common/src/crypto.rs
  oak_functions/client/java/BUILD
  oak_functions/client/java/src/AeadEncryptor.java
  oak_functions/client/java/src/AttestationClient.java
  oak_functions/client/java/src/KeyNegotiator.java
  oak_functions/client/java/src/Util.java
Labels: cla: yes

#2150 Set Java template in gRPC Attestation
  oak_functions/client/java/src/AttestationClient.java
Labels: cla: yes

#2143 Reorganize Oak Functions protos and clients
  examples/Cargo.lock
  examples/Cargo.toml
  examples/grpc_attestation/client/java/src/Main.java
  examples/grpc_attestation/client/rust/Cargo.toml
  examples/grpc_attestation/client/rust/src/main.rs
  examples/grpc_attestation/example.toml
  experimental/Cargo.lock
  experimental/grpc_attestation/Cargo.toml
  experimental/grpc_attestation/build.rs
  experimental/grpc_attestation/src/attestation.rs
  experimental/grpc_attestation/src/lib.rs
  experimental/grpc_attestation/src/main.rs
  experimental/grpc_attestation_client/rust/Cargo.toml
  experimental/grpc_attestation_client/rust/src/lib.rs
  oak_functions/client/java/BUILD
  oak_functions/client/java/src/AttestationClient.java
  oak_functions/client/rust/Cargo.lock
  oak_functions/client/rust/Cargo.toml
  oak_functions/client/rust/README.md
  oak_functions/client/rust/src/lib.rs
  oak_functions/client/rust/src/main.rs
  oak_functions/examples/Cargo.lock
  oak_functions/examples/key_value_lookup/example.toml
  oak_functions/examples/weather_lookup/client/java/BUILD
  oak_functions/examples/weather_lookup/client/java/README.md
  oak_functions/examples/weather_lookup/client/java/src/Main.java
  oak_functions/examples/weather_lookup/example.toml
  oak_functions/gcp/api_config.yaml.template
  oak_functions/load_test/Cargo.lock
  oak_functions/load_test/Cargo.toml
  oak_functions/load_test/src/main.rs
  oak_functions/loader/Cargo.lock
  oak_functions/loader/fuzz/Cargo.lock
  oak_functions/loader/src/grpc.rs
  oak_functions/proto/BUILD
  oak_functions/proto/invocation.proto
  oak_functions/proto/server.proto
  oak_functions/sdk/Cargo.lock
  oak_functions/sdk/test_utils/Cargo.toml
  oak_functions/sdk/test_utils/src/lib.rs
  scripts/deploy_oak_functions_api
Labels: cla: yes
