Repository project-oak/oak, pull requests merged in 2021-04, with the labels that each got.

#1165 Enable sccache for Rust compilation
  .github/workflows/ci.yaml
  Dockerfile
  runner/src/internal.rs
  scripts/docker_run
  scripts/runner
Labels: cla: yes

#1938 Update runner to remove generated files after running tests
  .github/workflows/ci.yaml
  runner/src/internal.rs
  runner/src/main.rs
Labels: cla: yes

#1925 Add a simple oak-functions loader
  oak_functions/loader/Cargo.lock
  oak_functions/loader/Cargo.toml
  oak_functions/loader/deny.toml
  oak_functions/loader/src/main.rs
  oak_functions/loader/src/server.rs
  oak_functions/loader/src/tests.rs
  oak_functions/loader/testdata/non-oak-minimal.wasm
  scripts/build_gh_pages
  scripts/common
Labels: cla: yes

#1942 Update hashes
  examples/aggregator/client/android/cpp/client.cc
  examples/aggregator/client/cpp/aggregator.cc
  examples/aggregator/config.toml
  examples/private_set_intersection/private_set_intersection_handler.sign
  scripts/runner
Labels: cla: yes

#1944 Add Dockerfile and deployment script for Functions
  oak_functions/.dockerignore
  oak_functions/Dockerfile
  scripts/deploy_oak_functions_loader
Labels: cla: yes

#1945 Split base and example images for Oak Functions
  oak_functions/.dockerignore
  oak_functions/Dockerfile
  oak_functions/loader/testdata/.dockerignore
  oak_functions/loader/testdata/Dockerfile
  scripts/deploy_oak_functions_loader
Labels: cla: yes

#1943 Add runner command for building oak-functions loader
  .github/workflows/ci.yaml
  .github/workflows/reproducibility.yaml
  Dockerfile
  oak_functions/loader/src/server.rs
  runner/src/internal.rs
  runner/src/main.rs
  scripts/build_reproducibility_index
Labels: cla: yes

#1947 Make Cargo crev a separate job
  .github/workflows/ci.yaml
Labels: cla: yes

#1913 Use more descriptive names for options specifying a path
  docs/programming-oak.md
  examples/abitest/client/cpp/abitest.cc
  examples/aggregator/README.md
  examples/aggregator/client/cpp/aggregator.cc
  examples/aggregator/scripts/run_client
  examples/chat/client/cpp/chat.cc
  examples/hello_world/client/cpp/hello_world.cc
  examples/http_server/client/rust/src/main.rs
  examples/http_server/example.toml
  examples/injection/client/cpp/injection.cc
  examples/private_set_intersection/client/cpp/private_set_intersection.cc
  examples/tensorflow/client/cpp/tensorflow.cc
  examples/translator/client/go/translator.go
  examples/trusted_database/client/cpp/trusted_database.cc
  oak/common/pkcs8.cc
  oak_runtime/src/lib.rs
  oak_runtime/src/node/wasm/mod.rs
  runner/src/main.rs
Labels: cla: yes

#1950 Perform multiple requests deploying on Cloud Run
  oak_functions/loader/testdata/Dockerfile
  scripts/deploy_oak_functions_loader
Labels: cla: yes

#1952 Define /invoke endpoint for Functions loader
  oak_functions/loader/src/server.rs
  oak_functions/loader/testdata/Dockerfile
  scripts/deploy_oak_functions_loader
Labels: cla: yes

#1954 Encapsulate Wasm state for Oak Functions loader
  oak_functions/loader/src/server.rs
  oak_functions/loader/src/tests.rs
Labels: cla: yes

#1959 Allow loading lookup data in Oak Functions loader
  oak_functions/loader/Cargo.lock
  oak_functions/loader/Cargo.toml
  oak_functions/loader/build.rs
  oak_functions/loader/src/main.rs
  oak_functions/loader/src/tests.rs
  oak_functions/proto/lookup_data.proto
Labels: cla: yes

#1967 Disable cargo udeps step in CI
  .github/workflows/ci.yaml
Labels: cla: yes

#1960 Download lookup data from URL instead of file
  oak_functions/loader/Cargo.toml
  oak_functions/loader/src/main.rs
  oak_functions/loader/src/server.rs
  oak_functions/loader/src/tests.rs
Labels: cla: yes

#1962 Use config file instead of command line flags
  oak_functions/Dockerfile
  oak_functions/examples/Cargo.lock
  oak_functions/examples/hello_world/README.md
  oak_functions/examples/hello_world/config.toml
  oak_functions/loader/Cargo.lock
  oak_functions/loader/Cargo.toml
  oak_functions/loader/src/main.rs
  oak_functions/loader/testdata/.dockerignore
  oak_functions/loader/testdata/Dockerfile
  oak_functions/loader/testdata/config.toml
  scripts/deploy_oak_functions_loader
Labels: cla: yes

#1972 Deploy hello world to Cloud Run
  oak_functions/examples/hello_world/.dockerignore
  oak_functions/examples/hello_world/Dockerfile
  oak_functions/loader/testdata/.dockerignore
  oak_functions/loader/testdata/config.toml
  scripts/deploy_oak_functions_loader
Labels: cla: yes

#1975 Use Duration time for benchmark
  oak_functions/loader/src/tests.rs
Labels: cla: yes

#1969 Use protobuf for OakStatus
  oak_functions/abi/Cargo.lock
  oak_functions/abi/Cargo.toml
  oak_functions/abi/build.rs
  oak_functions/abi/src/lib.rs
  oak_functions/examples/Cargo.lock
  oak_functions/loader/Cargo.lock
  oak_functions/loader/Cargo.toml
  oak_functions/loader/src/main.rs
  oak_functions/loader/src/server.rs
  oak_functions/loader/src/tests.rs
  oak_functions/proto/abi.proto
  oak_functions/sdk/Cargo.lock
  oak_functions/sdk/oak_functions/src/lib.rs
Labels: cla: yes

#1970 Use hello_world as benchmark
  oak_functions/examples/hello_world/module/src/lib.rs
  oak_functions/examples/hello_world/module/src/tests.rs
  oak_functions/loader/Cargo.lock
  oak_functions/loader/Cargo.toml
  oak_functions/loader/src/tests.rs
  oak_functions/sdk/oak_functions/src/lib.rs
Labels: cla: yes

#1976 Refresh lookup data at periodic interval
  oak_functions/examples/Cargo.lock
  oak_functions/examples/hello_world/config.toml
  oak_functions/loader/Cargo.lock
  oak_functions/loader/Cargo.toml
  oak_functions/loader/src/main.rs
  oak_functions/loader/src/tests.rs
  scripts/deploy_oak_functions_loader
Labels: cla: yes

#1957 Delete 'Parsed manifest files'
  runner/src/main.rs
Labels: cla: yes

#1968 Implement custom logger
  oak_functions/examples/Cargo.lock
  oak_functions/examples/hello_world/module/Cargo.toml
  oak_functions/examples/hello_world/module/src/tests.rs
  oak_functions/loader/Cargo.lock
  oak_functions/loader/Cargo.toml
  oak_functions/loader/src/lib.rs
  oak_functions/loader/src/logger.rs
  oak_functions/loader/src/main.rs
  oak_functions/loader/src/server.rs
  oak_functions/loader/src/tests.rs
Labels: Oak Functions, cla: yes

#1978 Replace dependency on asylo with absl
  oak/common/BUILD
  oak/common/hmac.cc
  oak/common/hmac.h
  oak/common/hmac_test.cc
  third_party/asylo/BUILD
  third_party/asylo/cleanup.h
  third_party/asylo/cleanup_test.cc
  third_party/asylo/statusor.cc
  third_party/asylo/statusor.h
Labels: cla: yes

#1974 Add binary to generate lookup data for test
  oak_functions/lookup_data_generator/Cargo.lock
  oak_functions/lookup_data_generator/Cargo.toml
  oak_functions/lookup_data_generator/README.md
  oak_functions/lookup_data_generator/deny.toml
  oak_functions/lookup_data_generator/src/main.rs
  scripts/generate_and_upload_lookup_data
Labels: cla: yes

#1982 Use new logger consistently
  oak_functions/loader/src/main.rs
Labels: Oak Functions, cla: yes

#1909 Migrate examples use linear handles (except abitest)
  examples/aggregator/client/android/cpp/client.cc
  examples/aggregator/client/cpp/aggregator.cc
  examples/aggregator/config.toml
  examples/aggregator/module/rust/Cargo.toml
  examples/chat/module/rust/Cargo.toml
  examples/injection/module/rust/Cargo.toml
  examples/private_set_intersection/handler_module/rust/Cargo.toml
  examples/private_set_intersection/main_module/rust/Cargo.toml
  examples/private_set_intersection/private_set_intersection_handler.sign
  examples/proxy_attestation/module/rust/Cargo.toml
  examples/translator/common/Cargo.toml
  examples/translator/module/rust/Cargo.toml
  examples/trusted_database/module/rust/Cargo.toml
Labels: cla: yes

#1981 Unify wasm compilation flags
  docs/programming-oak.md
  examples/Cargo.lock
  examples/abitest/abitest_common/Cargo.toml
  examples/abitest/module_0/rust/Cargo.toml
  examples/abitest/module_0/rust/tests/integration_test.rs
  examples/abitest/module_1/rust/Cargo.toml
  examples/abitest/oak_app_manifest.toml
  examples/aggregator/README.md
  examples/aggregator/module/rust/tests/integration_test.rs
  examples/aggregator/oak_app_manifest.toml
  examples/chat/module/rust/tests/integration_test.rs
  examples/chat/oak_app_manifest.toml
  examples/hello_world/module/rust/tests/integration_test.rs
  examples/hello_world/oak_app_manifest.toml
  examples/http_server/oak_app_manifest.toml
  examples/injection/oak_app_manifest.toml
  examples/private_set_intersection/README.md
  examples/private_set_intersection/main_module/rust/tests/integration_test.rs
  examples/private_set_intersection/oak_app_manifest.toml
  examples/proxy_attestation/oak_app_manifest.toml
  examples/translator/module/rust/tests/integration_test.rs
  examples/translator/oak_app_manifest.toml
  examples/trusted_database/module/rust/tests/integration_test.rs
  examples/trusted_database/oak_app_manifest.toml
  experimental/Cargo.lock
  experimental/benchmark/src/application/oak.rs
  oak_functions/loader/Cargo.lock
  oak_functions/loader/Cargo.toml
  runner/Cargo.lock
  runner/Cargo.toml
  runner/src/main.rs
  scripts/build_reproducibility_index
  sdk/Cargo.lock
  sdk/rust/oak/Cargo.toml
  sdk/rust/oak_app_build/src/main.rs
  sdk/rust/oak_tests/Cargo.toml
  sdk/rust/oak_tests/src/lib.rs
Labels: cla: yes

#1983 Enable dependabot for oak Functions loader
  .codecov.yml
  .github/dependabot.yml
  runner/src/main.rs
Labels: cla: yes

#1988 Unify logs for lookup data
  oak_functions/loader/src/main.rs
Labels: cla: yes

#1979 Add runner commands for oak-functions examples
  .github/workflows/ci.yaml
  examples/abitest/example.toml
  examples/aggregator/example.toml
  examples/chat/example.toml
  examples/hello_world/example.toml
  examples/http_server/example.toml
  examples/injection/example.toml
  examples/private_set_intersection/example.toml
  examples/proxy_attestation/example.toml
  examples/tensorflow/example.toml
  examples/translator/example.toml
  examples/trusted_database/example.toml
  oak_functions/examples/Cargo.lock
  oak_functions/examples/hello_world/client/client
  oak_functions/examples/hello_world/example.toml
  oak_functions/loader/Cargo.lock
  oak_functions/loader/Cargo.toml
  oak_functions/loader/src/main.rs
  runner/Cargo.lock
  runner/Cargo.toml
  runner/src/internal.rs
  runner/src/main.rs
Labels: cla: yes

#1990 ABI for lookups
  docs/oak_functions_abi.md
  oak_functions/abi/src/lib.rs
  oak_functions/examples/Cargo.lock
  oak_functions/examples/hello_world/module/Cargo.toml
  oak_functions/examples/hello_world/module/src/lib.rs
  oak_functions/examples/hello_world/module/src/tests.rs
  oak_functions/loader/Cargo.lock
  oak_functions/loader/src/lib.rs
  oak_functions/loader/src/lookup.rs
  oak_functions/loader/src/main.rs
  oak_functions/loader/src/server.rs
  oak_functions/loader/src/tests.rs
  oak_functions/proto/abi.proto
  oak_functions/sdk/Cargo.lock
  oak_functions/sdk/oak_functions/src/lib.rs
  oak_functions/sdk/test_utils/Cargo.toml
  oak_functions/sdk/test_utils/src/lib.rs
Labels: cla: yes

#1991 Implement internal Wasm allocator API
  docs/oak_functions_abi.md
  oak_functions/abi/src/lib.rs
  oak_functions/examples/Cargo.lock
  oak_functions/examples/hello_world/module/src/tests.rs
  oak_functions/loader/Cargo.lock
  oak_functions/loader/src/server.rs
  oak_functions/loader/src/tests.rs
  oak_functions/loader/testdata/non-oak-minimal.wasm
  oak_functions/proto/abi.proto
  oak_functions/sdk/Cargo.lock
  oak_functions/sdk/oak_functions/src/lib.rs
  oak_functions/sdk/test_utils/Cargo.toml
  oak_functions/sdk/test_utils/src/lib.rs
  runner/src/main.rs
  sdk/rust/oak_tests/src/lib.rs
Labels: cla: yes

#1996 Implement Weather Lookup functionality
  oak_functions/examples/Cargo.lock
  oak_functions/examples/hello_world/config.toml
  oak_functions/examples/hello_world/module/Cargo.toml
  oak_functions/examples/hello_world/module/src/lib.rs
  oak_functions/examples/hello_world/module/src/tests.rs
  oak_functions/loader/Cargo.lock
  oak_functions/loader/Cargo.toml
  oak_functions/loader/src/tests.rs
  oak_functions/lookup_data_generator/Cargo.lock
  oak_functions/lookup_data_generator/Cargo.toml
  oak_functions/lookup_data_generator/src/main.rs
  scripts/deploy_oak_functions_loader
  scripts/generate_and_upload_lookup_data_random
  scripts/generate_and_upload_lookup_data_weather
Labels: cla: yes

#2001 Fix Bazel in Android Docker
  android.Dockerfile
Labels: cla: yes

#1995 Automatically update oak_functions Cargo.lock
  oak_functions/examples/Cargo.lock
Labels: cla: yes

#2000 Cancel pending workflow runs
  .github/workflows/cancel.yml
Labels: cla: yes

#2004 Add explicit write permissions to actions
  .github/workflows/build_rust_docs.yaml
  .github/workflows/reproducibility.yaml
Labels: cla: yes

#2005 Add explicit codecov permissions
  .github/workflows/upload_coverage.yaml
Labels: cla: yes

#2010 Follow up fixes for #1991
  docs/oak_functions_abi.md
  oak_functions/examples/Cargo.lock
  oak_functions/examples/hello_world/module/src/tests.rs
  oak_functions/loader/Cargo.lock
  oak_functions/loader/src/server.rs
  oak_functions/loader/src/tests.rs
  oak_functions/sdk/Cargo.lock
  oak_functions/sdk/test_utils/Cargo.toml
  oak_functions/sdk/test_utils/src/lib.rs
Labels: cla: yes

#2013 Introduce utility to spawn background tasks
  oak_functions/examples/Cargo.lock
  oak_functions/examples/hello_world/module/src/tests.rs
  oak_functions/loader/Cargo.lock
  oak_functions/loader/src/main.rs
  oak_functions/loader/src/server.rs
  oak_functions/loader/src/tests.rs
  oak_functions/sdk/Cargo.lock
  oak_functions/sdk/test_utils/Cargo.toml
  oak_functions/sdk/test_utils/src/lib.rs
Labels: cla: yes

#2017 Stop ignoring RUSTSEC advisories
  examples/deny.toml
  experimental/deny.toml
  oak_client/deny.toml
  oak_loader/deny.toml
  oak_runtime/deny.toml
  oak_runtime/src/node/http/server.rs
  sdk/deny.toml
Labels: cla: yes, dependencies

#2012 Add Envoy Proxy Experiment
  experimental/envoy_proxy/README.md
  experimental/envoy_proxy/client/client.Dockerfile
  experimental/envoy_proxy/client/client.yaml
  experimental/envoy_proxy/client/client_localhost.yaml
  experimental/envoy_proxy/scripts/build.sh
  experimental/envoy_proxy/scripts/common.sh
  experimental/envoy_proxy/scripts/delete.sh
  experimental/envoy_proxy/scripts/deploy.sh
  experimental/envoy_proxy/scripts/run_client.sh
  experimental/envoy_proxy/scripts/run_server.sh
  experimental/envoy_proxy/server/server.Dockerfile
  experimental/envoy_proxy/server/server.yaml
Labels: cla: yes

#2019 Add logic to retry counts in case of possible leak
  examples/abitest/module_0/rust/tests/integration_test.rs
Labels: cla: yes

#2020 Run cargo-deny at the workspace level
  oak_functions/abi/deny.toml
  oak_functions/sdk/deny.toml
  runner/src/main.rs
Labels: cla: yes

#2018 Remove Wasm instance in WasmState
  oak_functions/loader/src/server.rs
Labels: cla: yes

#2025 Add loop to oak_main in oak_runtime integration test
  oak_runtime/tests/integration_test.rs
Labels: cla: yes

#2029 Update prometheus to latest published version
  examples/Cargo.lock
  experimental/Cargo.lock
  oak_loader/Cargo.lock
  oak_runtime/Cargo.lock
  oak_runtime/Cargo.toml
  sdk/Cargo.lock
Labels: cla: yes, dependencies

#1993 Runner refactor
  examples/abitest/example.toml
  examples/aggregator/example.toml
  examples/chat/example.toml
  examples/hello_world/example.toml
  examples/http_server/example.toml
  examples/injection/example.toml
  examples/private_set_intersection/example.toml
  examples/proxy_attestation/example.toml
  examples/tensorflow/example.toml
  examples/tls_attestation/example.toml
  examples/translator/example.toml
  examples/trusted_database/example.toml
  oak_functions/examples/hello_world/example.toml
  runner/src/examples.rs
  runner/src/files.rs
  runner/src/main.rs
Labels: cla: yes

#2011 Add policy to oak_functions_loader
  oak_functions/examples/Cargo.lock
  oak_functions/examples/hello_world/config.toml
  oak_functions/examples/hello_world/module/src/tests.rs
  oak_functions/loader/Cargo.lock
  oak_functions/loader/Cargo.toml
  oak_functions/loader/src/main.rs
  oak_functions/loader/src/server.rs
  oak_functions/loader/src/tests.rs
Labels: cla: yes

#2038 Rename hello world example to weather lookup
  oak_functions/examples/Cargo.lock
  oak_functions/examples/Cargo.toml
  oak_functions/examples/hello_world/.dockerignore
  oak_functions/examples/hello_world/README.md
  oak_functions/examples/hello_world/client/client
  oak_functions/examples/hello_world/example.toml
  oak_functions/examples/weather_lookup/.dockerignore
  oak_functions/examples/weather_lookup/Dockerfile
  oak_functions/examples/weather_lookup/README.md
  oak_functions/examples/weather_lookup/client/client
  oak_functions/examples/weather_lookup/config.toml
  oak_functions/examples/weather_lookup/example.toml
  oak_functions/examples/weather_lookup/module/Cargo.toml
  oak_functions/examples/weather_lookup/module/src/lib.rs
  oak_functions/examples/weather_lookup/module/src/tests.rs
  oak_functions/loader/src/main.rs
  oak_functions/loader/src/tests.rs
  scripts/deploy_oak_functions_loader
Labels: cla: yes

#2041 Support HTTP2 serving
  oak_functions/examples/Cargo.lock
  oak_functions/examples/weather_lookup/README.md
  oak_functions/examples/weather_lookup/client/client
  oak_functions/examples/weather_lookup/module/Cargo.toml
  oak_functions/examples/weather_lookup/module/src/tests.rs
  oak_functions/loader/Cargo.lock
  oak_functions/loader/Cargo.toml
  oak_functions/loader/src/server.rs
  oak_functions/loader/src/tests.rs
  scripts/deploy_oak_functions_loader
Labels: cla: yes

#2039 Add `write_log_message` ABI function
  docs/oak_functions_abi.md
  oak_functions/abi/src/lib.rs
  oak_functions/loader/src/server.rs
Labels: Oak Functions, cla: yes

#2044 Update run-cargo-tests to run benchmarks too
  .github/workflows/ci.yaml
  oak_functions/loader/src/tests.rs
  runner/src/internal.rs
  runner/src/main.rs
Labels: cla: yes

#2049 Add `write` permission on issues to reproducibility index workflow
  .github/workflows/reproducibility.yaml
Labels: cla: yes
