Repository project-oak/oak, pull requests merged in 2024-03, with the labels that each got.

#4860 Update nix deps
  .cargo/config.toml
  Cargo.lock
  buildconfigs/oak_echo_enclave_app.toml
  buildconfigs/oak_echo_raw_enclave_app.toml
  buildconfigs/oak_functions_enclave_app.toml
  buildconfigs/oak_ml_transparency_eval.toml
  buildconfigs/oak_orchestrator.toml
  buildconfigs/stage0_bin.toml
  enclave_apps/oak_functions_enclave_app/Cargo.toml
  flake.lock
  flake.nix
  micro_rpc_workspace_test/Cargo.lock
  oak_attestation_integration_tests/Cargo.toml
  oak_attestation_verification/Cargo.toml
  oak_containers_hello_world_untrusted_app/Cargo.toml
  oak_containers_launcher/Cargo.toml
  oak_containers_syslogd/Cargo.toml
  oak_crypto/Cargo.toml
  oak_docker_linux_init/Cargo.toml
  oak_functions/examples/key_value_lookup/module/Cargo.toml
  oak_functions_client/Cargo.toml
  oak_functions_enclave_service/Cargo.toml
  oak_grpc_utils/Cargo.toml
  oak_ml_transparency/runner/Cargo.toml
  oak_restricted_kernel_bin/deny.toml
  stage0_bin/deny.toml
  xtask/Cargo.toml
Labels: approval/any

#4910 Initial port of Chromium's noise_nk handshake.
  Cargo.lock
  enclave_apps/Cargo.lock
  micro_rpc_workspace_test/Cargo.lock
  oak_crypto/Cargo.toml
  oak_crypto/src/lib.rs
  oak_crypto/src/noise_handshake/README.md
  oak_crypto/src/noise_handshake/crypto_wrapper.rs
  oak_crypto/src/noise_handshake/error.rs
  oak_crypto/src/noise_handshake/mod.rs
  oak_crypto/src/noise_handshake/noise.rs
  oak_crypto/src/noise_handshake/tests.rs
  oak_restricted_kernel_bin/Cargo.lock
Labels: approval/all

#4930 Update nix deps (again)
  flake.lock
  oak_containers_kernel/configs/6.1.33/minimal.config
Labels: provenance:force-run

#4932 Build linux kernel with nix
  .gitignore
  flake.nix
  oak_containers_kernel/Makefile
  oak_containers_kernel/configs/6.1.33/minimal.config
  oak_containers_kernel/configs/6.1.33/minimal.config.old
Labels: provenance:force-run

#4935 Print binary digests in kokoro
  kokoro/build_binaries_oak_containers.sh
  kokoro/build_binaries_rust.sh
Labels: approval/any

#4940 Remove vmlinux target
  flake.nix
  oak_containers_kernel/Makefile
Labels: approval/any

#4941 Remove empty file
  empty
Labels: approval/any

#4949 Make linux kernel build reproducible
  FORCE_CI
  flake.nix
  oak_containers_kernel/configs/6.1.33/minimal.config
Labels: approval/any
